### ISSUE TITLE
Pip packages are not installed for Iceberg source plugin with Hive type

### ISSUE THREAD

**Issue by usmanovbf** [datahub-project/datahub#10058]
**Describe the bug**
Pip packages are not installed for Iceberg source plugin with hive type

**To Reproduce**
1. Create Iceberg ingestion source by the example below but without `type: hive`
2. Click `Save & Run`
3. Get an error about required `type` field
4. Update the recipe with `type: hive`
5. Click `Save & Run` button
7. See the errors (logs are below):
    1. ModuleNotFoundError: No module named 'thrift'
    2. pyiceberg.exceptions.NotInstalledError: Apache Hive support not installed: pip install 'pyiceberg[hive]'

**Expected behavior**
All pypi packages ` 'pyiceberg[hive]' thrift ` should be installed properly 

**Solution**

Execute `pip install` every time before execution of recipe

**Screenshots**
<img width="767" alt="image" src="https://github.com/datahub-project/datahub/assets/18537762/e042ae8c-1227-4826-b87f-77028e420295">

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma arm64
 - Browser Chrome
 - Version 122.0.6261.112

**Additional context**
1. Recipe:
```
source:
    type: iceberg
    config:
        env: PROD
        catalog:
            name: iceberg-catalog
            type: hive
            config:
                uri: 'https://hostname1:9083'
                s3.endpoint: 'https://hostname2'
                s3.access-key-id: '${secret1}'
                s3.secret-access-key: '${secret2}'
        table_pattern:
            allow:
                - 'test.*'
        profiling:
            enabled: false
```
3. Error logs: [exec-urn_li_dataHubExecutionRequest_1d2b870e-81e9-477a-8869-39505a9f2b3d.log](https://github.com/datahub-project/datahub/files/14608691/exec-urn_li_dataHubExecutionRequest_1d2b870e-81e9-477a-8869-39505a9f2b3d.log)
8. Even adding Extra Pip Libraries does not help
<img width="777" alt="Extra Pip Libraries9" src="https://github.com/datahub-project/datahub/assets/18537762/0cfed339-1bf1-4dff-b6bc-bfc658ff94c5">
9. Datahub version 0.12.1
10. As I see, it is not fixed in 0.13.0 from 0.12.1 https://github.com/datahub-project/datahub/commits/v0.12.1/metadata-ingestion/src/datahub/ingestion/source/iceberg
