### ISSUE TITLE
UI exception after adding a data contract

### ISSUE THREAD

**Issue by darthale** [datahub-project/datahub#10456]
After adding the data contract below via: `datahub datacontract upsert -f mq.yaml`, when navigating to the dataset in UI I get: `No enum constant com.linkedin.datahub.graphql.generated.AssertionType.FRESHNESS (code 400)`

**mq.yaml**
```yaml
entity: urn:li:dataset:(urn:li:dataPlatform:postgres,ml_db.public.mq,PROD)
version: 1
data_quality:
  - type: unique
```

I would have expected the data contract to show up in the UI under the validation tab. At the moment, the dataset is not accessible anymore because of said error. 

**Desktop (please complete the following information):**
 - OS: deployed datahub via the docker quickstart. OS: MacOS Sonoma
 - Browser: chrome
 - Version: v0.13.1
