### ISSUE TITLE
entity_types restrictions not working for structured properties

### ISSUE THREAD

**Issue by siladitya2** [datahub-project/datahub#10491]
**Describe the bug**
When we create a structure property with `entity_types` defined only `dataset`, we still can assign the structure property to other entity types(`dataflow`, `datajob` etc.) as well.

**To Reproduce**
1. Create a structure property with below-mentioned definition through CLI.
```
- id: my.test.SP01
  urn: urn:li:structuredProperty:my.test.SP01
  qualified_name: my.test.SP01
  display_name: SP01
  type: STRING
  cardinality: MULTIPLE
  entity_types:
    - dataset
```
2. Try to assign the above created Structure property to a `Dataflow` Entity.

`POST http://localhost:8080/openapi/v2/entity/dataset/urn:li:dataFlow:(airflow,test_instance1.demo-1%2F7,DEV)/structuredProperties`
Request Body:
```
{
  "properties": [
    {
      "propertyUrn": " urn: urn:li:structuredProperty:my.test.SP01",
      "values": [
        {"string": "bar"}
      ]
    }
```
3. No error is thrown, and the `structuredProperty` is assigned to the `Dataflow` entity.

**Expected behavior**
The structured property should not be assigned to the Dataflow entity.
As the entity types are defined only allow datasets.

**Screenshots**

**Desktop (please complete the following information):**
Datahub version - V0.13.0

**Additional context**
