### ISSUE TITLE
JSONL is not a supported file type

### ISSUE THREAD

**Issue by nopepper** [datahub-project/datahub#11028]
**Describe the bug**
I think this applies to both GCS and S3 sources. JSONL is supposed to be supported, but you can't specify `jsonl` as a file type under PathSpec. If you don't specify anything, it similarly breaks. Our files all have the extension `.jsonl`, so they won't be parsed if I use `json` as the file type.

**To Reproduce**
Add any file on GCS / S3 with the `.jsonl` extension:

```yaml
source:
  type: gcs
  config:
    credential:
      hmac_access_secret: ...
      hmac_access_id: ...
    path_specs:
      -
        include: 'gs://some-bucket/*.jsonl'
        file_types:
          - 'jsonl'
```

**Expected behavior**
`.jsonl` should be a recognized file type.

**Additional context**
By the way, the docs ask you to pass `file_types = '.*'` in case the extension is known, but that is not a valid configuration.
