### ISSUE TITLE
platform_instance is not shown for Superset platform assets

### ISSUE THREAD

**Issue by joshuaclausen** [datahub-project/datahub#11153]
**Describe the bug**
In DataHub, the Superset platform does not break down by platform_instance in the "Navigate" view.  Ingestion does include platform_instance (since [this merge](https://github.com/datahub-project/datahub/pull/9647)), but the DataHub display just has "Default" instead of one or more platform_instance names that I would expect.

**To Reproduce**
1. Ingest Superset metadata with a config such as this (in my case configured and ingested via the Ingest UI interface):
```
source:
    type: superset
    config:
        platform_instance: my_superset_instance
        connect_uri: 'https://superset.mydomain.com'
        username: admin
        password: '${superset_admin_password}'
        provider: db
```
3. From the DataHub instance click on the "Superset" platform
4. In the "Navigate" panel, click on "Dashboards" or "Charts" to expand; click on "Superset"
5. Notice it has only "Default".  This happens even when I have ingested multiple different Superset data sources via the

**Expected behavior**
There would be nodes beneath the Charts > Superset node, one for each unique "platform_instance" value, just as it works for other ingested data sources.  For example, the SqlAlchemy Platform works this way when I have it configured to ingest Dremio data via a config such as this:
```
source:
    type: sqlalchemy
    config:
        platform: dremio
        platform_instance: crimeboss
        connect_uri: 'dremio+flight://admin:${dremio_admin_password}@dremio.mydomain.com:32010/dremio?UseEncryption=false'
```

**Screenshots**
![image](https://github.com/user-attachments/assets/49488a88-5fc9-4d5e-96cb-b99a670256a9)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Chrome
 - 127.0.6533.89 (Official Build) (64-bit)

**Additional context**
- DataHub v0.13.3rc1
- I can see the platform_instance values in the Superset URNs in both the UI and via the datahub CLI, so I know the platform_instance values are being ingested as expected (since[ this pull request](https://github.com/datahub-project/datahub/pull/9647)).
