### ISSUE TITLE
MSSQL-ODBC ingester does not support all databases in source as suggested in the docs

### ISSUE THREAD

**Issue by T-Santos** [datahub-project/datahub#11185]
**Describe the bug**
Following the MSSQL-ODBC ingester docs described here
https://datahubproject.io/docs/generated/ingestion/sources/mssql/#config-details

> database (catalog). If set to Null, all databases will be considered for ingestion.

it appears that the ingester is intended to support this functionality but what I've seen in practice is

1. If `database` is omitted (Null) the ingester cannot connect to the server  a database is required to connect to.
2. If we instead specify the database under `options.connect_args` all databases get processed but the contents of the connection database gets loaded into each database as represented in datahub. 
3. using `sqlalchemy_uri` with the database selected processes every database but only ingested content from the db defined in the URI. 

**To Reproduce**
1. Identify or otherwise construct a MSSQL Source server with multiple application databases (ignoring databases such as 'master', 'model', 'msdb', 'tempdb', etc)
2. Create a python venv with the datahub mssql ingester installed (and supporting 3rd party libraries as necessary)
3. Construct a config resembling the following
```
source:
  type: mssql-odbc
  config:
    # Coordinates
    host_port: <server>:<port>
    options:
      connect_args:
        Trusted_Connection: 'yes'
        database: <application database to auth against>
....
```
4. run `datahub ingest run -c <path to config file.yaml>` to execute the configured ingester
5. See that the contents of the database specified in `connection_args` gets replicated across all databases in the MS SQL instance as represented in datahub

**Expected behavior**
The expectation is that the application would authenticate against the specified database to determine the set of all possible databases to consume and then the ingester would iterate over all databases configured and properly represent their objects in datahub. 

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser chrome
 - Version acryl-datahub==0.12.1.5

**Additional context**
I have a proposed code change that local testing seems to solve the problem that I'm happy to submit a PR for assuming I'm not misusing the application. Happy to try out other options if there is a standard pattern  that I've missed for scraping all databases from a MS SQL Server as the source.

**Comment by T-Santos** [comment]
@sleeperdeep I see you as a recent contributor in this space, using the ms sql ingestor, and I was wondering if you'd be able to opine on what I'm experiencing to understand if you're encountering similar or if it is misuse on my side. If your databases do not contain stored procedures I don't think you'd encounter this issue. 

The TL;DR of this issue is that I'm trying to run the ingestor with configuration to emit multiple databases within a MS SQL instance with one invocation of the ingester script but the content of the databases gets published to datahub under the database defined in the connection string (which is required).
```
    sqlalchemy_uri: 'mssql+pyodbc://my_server/master?Trusted_Connection=yes&driver=ODBC+Driver+17+for+SQL+Server'
```
if I have databases A, B with stored procedures, the'll get emitted using `master` as shown in the connection string, not `A` or `B` - the database where the objects are actually found. The DataJobs and DataFlows that get created are wrong but the Datasets are correct. 

I'm running something like this
```
$ datahub ingest run -c mssql_sample_recipe.yaml -n
```
with a config that looks like this `mssql_sample_recipe.yaml`
```
source:
  type: mssql-odbc
  config:
    host_port: my_server:2001    
    database_pattern: {'allow': ['A', 'B'], 'ignoreCase': True}
    include_jobs: False
    convert_urns_to_lowercase: True  # need to normalize URNS because other sources are case insensitive and we can't mix and match
    env: DEV
    platform_instance: my_server
    sqlalchemy_uri: 'mssql+pyodbc://my_server:2001/master?Trusted_Connection=yes&driver=ODBC+Driver+17+for+SQL+Server'

sink:
  type: console
```

in the console output i see stuff like the below, showing `master` as the database but they are actually objects in A and B. It might just be a bug in how the `dataFlow` determines the `database`, I'm going to chase this but would be good if you'd be able to confirm. 
```
'dataJob': ['urn:li:dataJob:(urn:li:dataFlow:(mssql,my_server.master.dbo.stored_procedures,DEV),sproc_1)',
                          'urn:li:dataJob:(urn:li:dataFlow:(mssql,my_server.master.dbo.stored_procedures,DEV),sproc_2)',
```

Are you encountering this?

**Comment by sleeperdeep** [comment]
Hi @T-Santos! 
I've not faced it before, because I've not used sqlalchemy_uri for connection (only used direct fileds like database, host_port and etc.).

But I've checked it. And true, it is bug.

[Iteration over database here](https://github.com/datahub-project/datahub/blob/3c717bac36fd6dc6c1c2579e8f4b633a2d3c4e61/metadata-ingestion/src/datahub/ingestion/source/sql/mssql/source.py#L960-L966). But because you are using sqlalchemy_uri, [current_db param are ignored here](https://github.com/datahub-project/datahub/blob/3c717bac36fd6dc6c1c2579e8f4b633a2d3c4e61/metadata-ingestion/src/datahub/ingestion/source/sql/mssql/source.py#L143).
As a result, [get_db_name method](https://github.com/datahub-project/datahub/blob/3c717bac36fd6dc6c1c2579e8f4b633a2d3c4e61/metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py#L414-L422) will return you database taht you've specified in sqlalchemy_uri permanently for all workunits.

<img width="917" height="181" alt="Image" src="https://github.com/user-attachments/assets/97dab3a0-fab6-4334-b7fe-632045274ef5" />

@yoonhyejin FYI

**Comment by T-Santos** [comment]
Thank you @sleeperdeep for the quick response and confirming what I was experiencing. I'll try your approach -  using the dedicated connection configuration fields instead of `sqlalchemy_uri` and see if I get better behavior and I'll report back.

**Comment by T-Santos** [comment]
I can confirm that when I use the dedicated connection fields as @sleeperdeep so kindly suggested, it does provide the expected behavior.  
Using the following fields instead of `sqlalchemy_uri` does the trick for now. 
```
    use_odbc: True
    uri_args:
      driver: "ODBC Driver 17 for SQL Server"
      Trusted_Connection: "yes"
      database: "master"
```
That said though, I do see `convert_urns_to_lowercase: True` being ignored for the database name of the urn now which are containing mixed-case letters....but I'll investigate that separately to this bug report and enter a new one if required.
