### ISSUE TITLE
Platform Instance not working with powerbi-report-server

### ISSUE THREAD

**Issue by pankajmahato-visa** [datahub-project/datahub#11336]
**Describe the bug**
Failed to configure the source (powerbi-report-server): 1 validation error for PowerBiReportServerDashboardSourceConfig
platform_instance
  extra fields not permitted (type=value_error.extra)

**To Reproduce**
1. Create recipe for powerbi
```
source:
  type: powerbi-report-server
  config:
    platform_instance: POWERBI.OCE.DEV
    username: '${POWERBI_USERNAME}'
    password: '${POWERBI_PASSWORD}'
    workstation_name: corpdev
    host_port: 'powerbirsdev.trusted.visa.com:443'
    server_alias: server_alias
    env: DEV
    report_virtual_directory_name: Reports
    report_server_virtual_directory_name: ReportServer
    extract_ownership: true
    ownership_type: TECHNICAL_OWNER
pipeline_name: "POWERBI DEV"
sink:
  type: datahub-rest
  config:
    server: '${DATAHUB_GMS_HOST}'
    token: '${DATAHUB_GMS_TOKEN}'
    max_threads: 1
```

**Expected behavior**
PoweBi Dashboards should be ingested with the provided Platform Instance
