### ISSUE TITLE
Unable to ingest Json schema 

### ISSUE THREAD

**Issue by lekhamaru** [datahub-project/datahub#11509]
While evaluating DataHub, I'm trying to ingest Json schemas using CLI. My recipe file is as follows
---------------------------------------------------------
pipeline_name: json_schema_ingestion
source:
  type: json-schema
  config:
    path: https://json.schemastore.org/petstore-v1.0.json # e.g. https://json.schemastore.org/petstore-v1.0.json
    platform: SchemaRegistry # e.g. schemaregistry
    # platform_instance: <add a platform_instance if there are multiple schema repositories>
    stateful_ingestion:
      enabled: true # recommended to have this turned on
-------------------------------------------------------------
Error log while executing the command
datahub ingest -c <recipe file>
I'm getting the error as placed in the log file
[log.txt](https://github.com/user-attachments/files/17194814/log.txt)

**Comment by jjoyce0510** [comment]
Hi there! Do you mind trying the same with Python version 3.10. I can tell from the logs your version of Python is 3.12.4, which is not officially supported yet by the ingestion framework.

Let us know how it goes!

Cheers
John

**Comment by lekhamaru** [comment]
Sure. Will check and revert.

**Comment by lekhamaru** [comment]
I checked with python version 3.8.10 but still facing the same issue.
[logwithpythonversion3.8.10.txt](https://github.com/user-attachments/files/17200382/logwithpythonversion3.8.10.txt)

**Comment by treff7es** [comment]
@lekhamaru I'm unable to reproduce this issue locally.
Can you please run a `pip freeze` and paste the package versions here?

Here is how I tested using `Python 3.9.10`:
1. `pip install "acryl-datahub[json-schema]"`
2. Creating this recipe:
```
pipeline_name: json_schema_ingestion
source:
  type: json-schema
  config:
    path: "http://json.schemastore.org/petstore-v1.0.json" # e.g. json.schemastore.org/petstore-v1.0.json
    platform: SchemaRegistry # e.g. schemaregistry
    # platform_instance:
    stateful_ingestion:
      enabled: true # recommended to have this turned on
```

3. Running:
`datahub ingest -c json_schema_ingest.dhub.yaml`
