### ISSUE TITLE
There is no v0.14.1 docker image tag for the 

### ISSUE THREAD

**Issue by Linux-oiD** [datahub-project/datahub#11655]
**Describe the bug**
I see that there is no v0.14.1. tag for the **acryldata/datahub-postgres-setup** container in the Docker hub.
I do see an updated image for the **acryldata/datahub-mysql-setup** but what about postgres? It's braking the Helm-based deployment with default values because it expects that all components will have the same image tags.

**Expected behavior**
All DataHub components should have the same release tag, including **acryldata/datahub-postgres-setup**

**Comment by MatMoore** [comment]
This prevented us from updating as well, giving us the following error

```
Error: UPGRADE FAILED: release datahub failed, and has been rolled back due to atomic being set: pre-upgrade hooks failed: 1 error occurred:
	* timed out waiting for the condition
```

I worked around it by setting `image.tag` to the previous working version in the helm values.

```yaml
postgresqlSetupJob:
  enabled: true
  image:
    repository: acryldata/datahub-postgres-setup
    # tag: "v0.11.0" # defaults to .global.datahub.version
    tag: v0.14.0.2
```
