### ISSUE TITLE
Validation Error During Dataset Upsert Using DataHub CLI

### ISSUE THREAD

**Issue by zeta9044** [datahub-project/datahub#11667]
**Describe the bug**
 I encountered a validation error when trying to upsert a dataset using the DataHub CLI. The error occurs while running the ```datahub dataset upsert -f dataset.yaml``` command. Below is the detailed information about the dataset and environment.

**Dataset.yaml**
```
urn: urn:li:dataset:(urn:li:dataPlatform:snowflake,long_tail_companions.adoption.actuating,PROD)
name: ACTUATING
schema_metadata:
  fields:
    - id: pk
      urn: urn:li:schemaField:(urn:li:dataset:(urn:li:dataPlatform:snowflake,long_tail_companions.adoption.actuating,PROD),pk)
      type: "SchemaFieldDataTypeClass({'type': NumberTypeClass({})})"
      nativeDataType: NUMBER(1,0)
      nullable: true
      recursive: false
properties: {}
subtypes:
  - Table
```

**error message**
```
1 validation error for Dataset
schema
  Field required [type=missing, input_value={'urn': 'urn:li:dataset:(..., 'subtypes': ['Table']}, input_type=CommentedMap]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
```
**execute env**
 - OS: Ubuntu 22 LTS
 - Version: acryl-datahub, version 0.14.1.2
