### ISSUE TITLE
Ingest DBT Contract Information as a DataHub Data Contract

### ISSUE THREAD

**Issue by matthew-coudert-cko** [datahub-project/datahub#11927]
We (Checkout.com) have started using DataHub's contract feature more intensely over the past few months, and have implemented a custom mapping between DBT contracts and DataHub's data contract feature. We propose implementing this as a part of the native DBT Core ingestion with the following functionality:

1. DBT Contracts prevent breaking changes (column removals or column type changes), so they are equivalent to a schema contract in DataHub.
2. DBT Tests assigned with an arbitrary tag (default `contract`) have their assertion added to the data contract.

Example DBT Yaml:
```yaml
- name: dbt_contract_test_view
  description: This view is used to test the data contract checks for the dbt models.
  config:
    contract:
      enforced: true # this adds a schema contract to the DataHub data contract.
  columns:
      - name: urn
        data_type: text
        description: The urn of the object.
        data_tests:
          - unique
             tags: ['contract'] # this is included in the data contract
          - not_null # this is not
```
