### ISSUE TITLE
Although the source ingestion process completes successfully, no data appears in Neo4j.

### ISSUE THREAD

**Issue by zeta9044** [datahub-project/datahub#12273]
**Describe the bug**
When I set up a graph DB using Neo4j and executed source ingestion from PostgreSQL, there is data in MySQL but no data appears in Neo4j.

**To Reproduce**
install
```
datahub docker quickstart --graph-service-impl neo4j --version v0.14.1
```

postgres-dev.yml
```
source:
    type: postgres
    config:
        host_port: 'localhost:5432'
        database: postgres
        username: usr
        include_tables: true
        include_views: true
        password: usr

sink:
  type: datahub-kafka
  config:
    connection:
      bootstrap: 'localhost:9092'
      schema_registry_url: 'http://localhost:8081'
```
```
datahub ingest -c postgres-dev.yml
```
```
MATCH (n) 
RETURN count(n);

result = 0
```

**Expected behavior**
```
MATCH (n) 
RETURN count(n);

not result = 0 but result > 0
```

**Desktop (please complete the following information):**
 - OS: ubuntu 22
