### ISSUE TITLE
POST operation named ingestProposalBatch not supported on resource 'com.linkedin.metadata.resources.entity.AspectResource'

### ISSUE THREAD

**Issue by MaddyAustin4** [datahub-project/datahub#12315]
**Describe the bug**
We are using dbt as a source and ingesting to datahub. When migrating to 0.15.0 from 0.13.1 the ingestion starts failing with the error 

```
error': 'Unable to emit metadata to DataHub GMS: POST operation named ingestProposalBatch not supported on resource 'com.linkedin.metadata.resources.entity.AspectResource' URI: '/aspects?action=ingestProposalBatch'

'exceptionClass': 'com.linkedin.restli.server.RestLiServiceException'
```

**To Reproduce**
I'm unsure whats actually causing the issue. 

Recipe:

```
source:
  type: "dbt"
  config:
    stateful_ingestion:
      enabled: true
    test_results_path: "/dbt/target/run_results.json"
    manifest_path: "/dbt/target/manifest.json"
    sources_path: "/dbt/target/sources.json"
    catalog_path: "/dbt/target/catalog.json"
    target_platform: "snowflake"

pipeline_name: dbt_pipeline
```

`datahub ingest -c datahub/recipe.yml`

**Expected behavior**
ingestion to work as usual post upgrade

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux/X86_64

**Additional context**
