### ISSUE TITLE
Ingestion Fails for Redshift Serverless with "Permission Denied" on stl_insert

### ISSUE THREAD

**Issue by aniketwdubey** [datahub-project/datahub#12415]
I am using Redshift Serverless as the source for DataHub metadata ingestion. When running the ingestion pipeline, the process fails with a `Permission denied for relation stl_insert error`. This seems to be caused by Redshift Serverless's restricted access to STL, STV, SVCS, and SVL system tables, as noted in the AWS documentation (linked below).

**Recipe File**
```
source:
  type: redshift
  config:
    host_port: <my-workgroup>.redshift-serverless.amazonaws.com:5439
    database: mydatabase
    username: <username>
    password: <password>
sink:
  type: file
  config:
    filename: dump_me.json
```

**Error Output**

`[2025-01-21 18:33:57,578] ERROR {datahub.ingestion.source.redshift.exception:55} - Permission denied: Failed to extract metadata due to insufficient permissions.Permission denied: Failed to extract metadata due to insufficient permissions.: {'S': 'ERROR', 'C': '42501', 'M': 'permission denied for relation stl_insert', 'F': '/opt/brazil-pkg-cache/packages/RedshiftPADB/RedshiftPADB-1.0.5722.0/AL2_aarch64/generic-flavor/src/src/pg/src/backend/catalog/aclchk.c', 'L': '3588', 'R': 'aclcheck_error'}`

According to [this AWS discussion](https://repost.aws/questions/QUr1ywNL6kQPOglpmRVMCtCA/redshift-superuser-permission-denied-to-stl-tables), Redshift Serverless does not allow querying STL, STV, SVCS, SVL, and some SVV system tables and views, except for certain SVV tables.
