### ISSUE TITLE
UI Ingestion but the task was never scheduled

### ISSUE THREAD

**Issue by lu-xiaoshuang** [datahub-project/datahub#12468]
I tried to run an UI Ingestion but the task was never scheduled.

```
source:
    type: mysql
    config:
        host_port: 'mysql-address:mysql-port'
        database: null
        username: mysql-username
        include_tables: true
        include_views: true
        profiling:
            enabled: true
            profile_table_level_only: true
        stateful_ingestion:
            enabled: true
        password: mysql-password
sink:
    type: datahub-rest
    config:
        server: 'http://metadata-service-address:metadata-service-port'
        token: blah-blah-blah
```

![Image](https://github.com/user-attachments/assets/58184b70-3336-4060-b2dd-107ad7129aa9)

By the way, docs on UI ingestion are confusing.

1. Docs Home => Deployment => Deployment Guides => Deploying with Docker (https://datahubproject.io/docs/docker)```[acryldata/datahub-actions](https://hub.docker.com/r/acryldata/datahub-actions). Do not use acryldata/acryl-datahub-actions as that is deprecated and no longer used.
```

2. Docs Home => Features => Ingestion (https://datahubproject.io/docs/ui-ingestion)
```
I see 'N/A' when I try to run ingestion. What do I do?
If you see 'N/A', and the ingestion run state never changes to 'Running', this may mean that your executor (datahub-actions) container is down.

This container is responsible for executing requests to run ingestion when they come in, either on demand on a particular schedule. You can verify the health of the container using docker ps. Moreover, you can inspect the container logs using by finding the containoCodeer id for the datahub-actions container and running docker logs <container-id>.
```

3. Source Code Root Directory/docker/datahub-actions (https://github.com/datahub-project/datahub/tree/master/docker/datahub-actions)
This is directoy is almost empty. There is no dockerfile.
