### ISSUE TITLE
Power BI Integration - unable to extract lineage

### ISSUE THREAD

**Issue by kelsen** [datahub-project/datahub#12492]
Unable to extract lineage from M-Query expression.

Data source configuration:
```
source:
    type: powerbi
    config:
        tenant_id: hidden 
        client_id: hidden
        client_secret: '${powerbi_api}'
        stateful_ingestion:
            enabled: true
        extract_endorsements_to_tags: true
        admin_apis_only: false
        extract_column_level_lineage: true
        extract_dashboards: false
        extract_dataset_schema: true
        server_to_platform_instance:
            DB_HOST:
                platform_instance: sisplan_prod
                env: PROD
```

Context:
```
table-full-name=Vendas.fVendas, expression = let
    Origem = PostgreSQL.Database(DB_HOST, "13964P"),
    #"Navegação 1" = Origem{[Schema = "sisplan", Item = "fato_vendas"]}[Data],
    #"Colunas Renomeadas" = Table.RenameColumns(#"Navegação 1",{{"cd_empresa", "codigo empresa"}, {"cd_cliente", "codigo cliente"}, {"cd_representante", "codigo representante"}, {"dt_emissao", "dt emissao"}, {"qt_vendida", "qt vendida"}, {"qt_pendente", "qt pendente"}, {"vl_venda", "vl venda"}, {"unidade_negocio", "unidade negocio"}, {"deposito", "codigo deposito"}}),
    Personalizar1 = Table.SelectRows(#"Colunas Renomeadas", each DateTime.From([dt emissao]) >= RangeStart and DateTime.From([dt emissao]) < RangeEnd)
in
    Personalizar1, output-variable=Personalizar1 not found in table expression
```

[exec-urn_li_dataHubExecutionRequest_d8adac3b-1610-45f7-a049-29709348c131.log](https://github.com/user-attachments/files/18591279/exec-urn_li_dataHubExecutionRequest_d8adac3b-1610-45f7-a049-29709348c131.log)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 132.0.6834

Docker v.0.15.0
