### ISSUE TITLE
Druid ingestion using platform_instance creates a duplicate in the dataset URN

### ISSUE THREAD

**Issue by Rasnar** [datahub-project/datahub#12546]
**Describe the bug**
When using the `source` with `druid` and with the `platform_instance` set, the instance platform name is added twice to the final URN.

**To Reproduce**
Using the datahub cli ingest `datahub ingest -c <path to yaml content shown below>`.

Using the following recipe:
```
source:
  type: druid
  config:
    username: ${USER}
    password: ${PASS}
    host_port: ${DRUID_ENDPOINT}
    scheme: druid+https
    env: PROD
    platform_instance: "team1"
    # Ignore internal tables
    schema_pattern:
      deny: ["^(lookup|sysgit|view|sys).*"]
    stateful_ingestion:
      enabled: True # False by default
```

Let's say that the Druid has a database named `druid-metrics`, then I get an URN like this:
```
'urn:li:dataset:(urn:li:dataPlatform:druid,team1.team1.druid-metrics,PROD)'
```
We can see the `team1` entry being set twice in the dataset path.

If I remove the `platform_instance`, the path is like this, which is correct:
```
'urn:li:dataset:(urn:li:dataPlatform:druid-metrics,PROD)'
```

**Expected behavior**

Based on the example above, the URN should only have the platform_instance once in the name, which would result on something like this:
```
'urn:li:dataset:(urn:li:dataPlatform:druid,team1.druid-metrics,PROD)'
```

**Screenshots**

**Desktop (please complete the following information):**
We are currently using [v0.14.1](https://github.com/datahub-project/datahub/releases/tag/v0.14.1), but I also tested with the CLI `v0.15.1` and the result is the same, the platform_instance is added twice to the final URN.

**Additional context**

In the druid case, the platform_instance is added here:
https://github.com/datahub-project/datahub/blob/master/metadata-ingestion/src/datahub/ingestion/source/sql/druid.py#L54

but maybe it's also added somewhere else on top of this call, but I don't know enough the code to know if this platform_instance is added somewhere else.
