### ISSUE TITLE
Stored procedures are not ingested into specified domain

### ISSUE THREAD

**Issue by ttekampe** [datahub-project/datahub#12586]
**Describe the bug**
Stored procedures are not ingested into specified domain.

**To Reproduce**
1. you need a database with stored procedures
2. run a ingestion job that specifies the domain into which the data shall go
example:
```
source:
  type: mssql
  config:
    host_port: 'localhost'
    database: MY_DATABASE
    username: MY_DATABASE_USER_NAME
    password: MY_DATABASE_USER_PASSWORD
    include_stored_procedures: true
    include_stored_procedures_code: true
    domain:
      'My Domain':
        allow:
          - '.*'
```

**Expected behavior**
All ingested objects should go under the 'My Domain' domain.
For tables and views this works nicely. Stored procedures however do not get a domain assigned

**Additional context**
* Datahub version `0.15.0`
* CLI version `0.15.0.5`
