### ISSUE TITLE
GMS restart breaks authN with Frontend and through API Keys

### ISSUE THREAD

**Issue by npgretz** [datahub-project/datahub#12707]
**Describe the bug**
When deploying using the Helm Chart v0.43.6 on K8's, whenever the GMS pod is restarted authN fails with previously working credentials and API Keys. In order to restore access, I then have to restart the Frontend pod and recreate the API Keys.

**To Reproduce**
1. Deploy with GMS and use GMS for authN: METADATA_SERVICE_AUTH_ENABLED='true' for the GMS and Frontend pods.
2. OIDC SSO AuthN works through GMS/Frontend and API keys work for REST API AuthN.
3. GMS pod is restarted due to failure
4. GMS pod no longer accepts credentials or API Keys:

With OIDC SSO login:
```
WARN c.d.a.a.AuthenticatorChain:106 - Authentication chain failed to resolve a valid authentication. Errors: [(com.datahub.authentication.authenticator.DataHubSystemAuthenticator,Failed to authenticate inbound request: Provided credentials do not match known system client id & client secret. Check your configuration values...), (com.datahub.authentication.authenticator.DataHubTokenAuthenticator,Failed to authenticate inbound request: Authorization header missing 'Bearer' prefix.), (com.datahub.authentication.authenticator.HealthStatusAuthenticator,Failed to authenticate inbound request: Authorization not allowed. Non-health check endpoint.)]
```
With API Key:
```
401 Client Error: Unauthorized for url: https://<URL of GMS>:8080/aspects?action=ingrestProposalBatch
```

**Expected behavior**
The GMS pod should be able to be recreated and restarted independently of the Frontend pod. API Keys should also continue to work after the GMS pod is recreated.

**Desktop (please complete the following information):**
 - Browser: Firefox
 - Version: Helm Chart v0.4.36; App v0.14.1

**Additional context**
OIDC SSO configured and API Keys are created for REST API calls to DataHub.

**Comment by npgretz** [comment]
Can anyone provide more insight into why the API keys are no longer working after a GMS restart or in what way the GMS, and Frontend pods are coupled?

**Comment by NoamMosko** [comment]
@npgretz I encountered a similar issue—not on the same Helm chart version, but I reviewed your default values, and it appears quite similar.

By default, the following settings are applied:

[values.yaml](https://artifacthub.io/packages/helm/datahub/datahub/0.4.36?modal=values&path=global.datahub.metadata_service_authentication.enabled)

```
metadata_service_authentication:
  enabled: true
  systemClientId: "__datahub_system"
  systemClientSecret:
    secretRef: "datahub-auth-secrets"
    secretKey: "system_client_secret"
  tokenService:
    signingKey:
      secretRef: "datahub-auth-secrets"
      secretKey: "token_service_signing_key"
    salt:
      secretRef: "datahub-auth-secrets"
      secretKey: "token_service_salt"
  # Set to false if you'd like to provide your own auth secrets
  provisionSecrets:
    enabled: true
    autoGenerate: true
    annotations: {}
```


The issue arises because these secrets are regenerated every time there is a restart. This leads to inconsistencies—either the frontend and actions components share the same keys and secrets while GMS ends up with different ones, or vice versa, depending on which service was restarted.

Solution:
We resolved this by setting provisionSecrets to false, allowing us to provide our own secrets instead of relying on the default datahub-auth-secrets. This ensures consistency across restarts and prevents the regeneration issue.


Let me know if that helped you.
