### ISSUE TITLE
using glue source with aws_role

### ISSUE THREAD

**Issue by alberttwong** [datahub-project/datahub#13529]
**Describe the bug**
Instead of using access and secret key, I am trying to use aws_role

**To Reproduce**

```
source:
    type: glue
    config:
        aws_region: us-west-2
        aws_role: 'arn:aws:iam::582558643208:role/eks-node-role-5fea1368'

```

error is 
```
datahub.ingestion.run.pipeline.PipelineInitError: Failed to configure the source (glue): No credentials available for role assumption
```

**Expected behavior**

I expected that this would work. 

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by alberttwong** [comment]
I've currently established connectivity using AWS access keys, a secret key, and a session token. However, I'm trying to configure access using IAM roles instead. This is crucial because our access keys rotate daily, making role-based authentication a more permanent and manageable solution.

```
source:
    type: glue
    config:
        aws_region: us-west-2
        aws_access_key_id: xxxx
        aws_secret_access_key: yyyyy
        aws_session_token: zzz
```
