### ISSUE TITLE
Issues Adding MongoDB data source hosted on Atlas

### ISSUE THREAD

**Issue by rudolph9** [datahub-project/datahub#13735]
**Describe the bug**

I have the following recipe for connecting to mongo:

```
source:
    type: mongodb
    config:
        connect_uri: 'mongodb+srv://user:pass@db.url.mongodb.net?authSource=admin&replicaSet=atlas-abc123-shard-0&readPreference=secondary&appname=DataHubSethLoca&ssl=true'
        enableSchemaInference: true
        useRandomSampling: true
        maxSchemaSize: 300
        hostingEnvironment: ATLAS
```

But I run into the following error:

```
<class 'pymongo.errors.OperationFailure'>: not authorized on db_name to execute command { aggregate: "system.views", pipeline: [ { $addFields: { temporary_doc_size_field: { $bsonSize: "$$ROOT" } } }, { $match: { temporary_doc_size_field: { $lt: 16793600 } } }, { $project: { temporary_doc_size_field: 0 } }, { $sample: { size: 1000 } } ], allowDiskUse: true, cursor: {}, lsid: { id: UUID("56476bcc-36c0-4f6e-bfaf-abc026595464") }, $clusterTime: { clusterTime: Timestamp(1749492390, 1), signature: { hash: BinData(0, AD26D968C85CD50F60354E4AE08CA83ABCD), keyId: 7475805141816311810 } }, $db: "db_name", $readPreference: { mode: "secondary" } }, full error: {'ok': 0.0, 'errmsg': 'not authorized on db_name to execute command { aggregate: "system.views", pipeline: [ { $addFields: { temporary_doc_size_field: { $bsonSize: "$$ROOT" } } }, { $match: { temporary_doc_size_field: { $lt: 16793600 } } }, { $project: { temporary_doc_size_field: 0 } }, { $sample: { size: 1000 } } ], allowDiskUse: true, cursor: {}, lsid: { id: UUID("56476bcc-36c0-4f6e-bfaf-abc026595464") }, $clusterTime: { clusterTime: Timestamp(1749492390, 1), signature: { hash: BinData(0, AD26D968C85CD50F60354E4AE08CA838042458FC), keyId: 7475805141816311810 } }, $db: "db_name", $readPreference: { mode: "secondary" } }', 'code': 13, 'codeName': 'Unauthorized', '$clusterTime': {'clusterTime': Timestamp(1749492390, 1), 'signature': {'hash': b'\xad&\xd9h\xc8\\\xd5\x0f`5NJ\xe0\x8c\xa88\x04$X\xfc', 'keyId': 7475805141816311810}}, 'operationTime': Timestamp(1749492390, 1)}
```

I've tried troubleshooting this by configuring the user on MongoDB Atlas to have full read/write access to every database and even DB admin permissions, but the issue persists. On the DataHub side, I've attempted omitting the problematic database and using various other filters to bypass the issue, but without success. Ultimately, I'm limited in MongoDB Atlas in terms of creating users—specifically, I'm unable to create one with aggregate permissions.

Any help would be greatly appreciated.
