### ISSUE TITLE
Custom Search with prefix ranking does not prioritise required entities

### ISSUE THREAD

**Issue by mitchdawson1982** [datahub-project/datahub#13781]
**Describe the bug**
Having followed examples to enable custom search and configure prefix based ranking [here](https://docs.datahub.com/docs/how/search#example-4-entity-ranking) for **containers**, we don't receive a result set with containers boosted (at the top).

- We are using / landing on the `.*` regex pattern (at the bottom)
- Datahub v1.1.0 (latest chart)
- Opensearch 2.9
- GMS environment Variables:
```
ELASTICSEARCH_QUERY_CUSTOM_CONFIG_FILE=/datahub/datahub-gms/resources/search/search_config.yml
ELASTICSEARCH_HOST=opensearch-proxy-service-a7ah7efa.data-platform-datahub-catalogue-dev.svc.cluster.local
ELASTICSEARCH_BULKPROCESSOR_REQUESTSLIMIT=250
ELASTICSEARCH_SEARCH_GRAPH_TIMEOUT_SECONDS=50
ELASTICSEARCH_SEARCH_GRAPH_BATCH_SIZE=1000
ELASTICSEARCH_SEARCH_GRAPH_MAX_RESULT=10000
ELASTICSEARCH_PORT=8080
ELASTICSEARCH_USE_SSL=false
ELASTICSEARCH_QUERY_MAX_TERM_BUCKET_SIZE=100
ELASTICSEARCH_QUERY_EXACT_MATCH_PREFIX_FACTOR=1.6
ELASTICSEARCH_QUERY_EXACT_MATCH_EXCLUSIVE=false
ELASTICSEARCH_QUERY_EXACT_MATCH_ENABLE_STRUCTURED=true
ELASTICSEARCH_QUERY_EXACT_MATCH_CASE_FACTOR=0.7
SKIP_ELASTICSEARCH_CHECK=false
ELASTICSEARCH_INDEX_BUILDER_MAPPINGS_REINDEX=true
ELASTICSEARCH_QUERY_EXACT_MATCH_WITH_PREFIX=true
ELASTICSEARCH_INDEX_BUILDER_SETTINGS_REINDEX=true
ELASTICSEARCH_QUERY_EXACT_MATCH_FACTOR=2
ELASTICSEARCH_QUERY_CUSTOM_CONFIG_ENABLED=true
```

- Full Search Configuration: `cat /datahub/datahub-gms/resources/search/search_config.yml`

```
queryConfigurations:
- exactMatchQuery: false
  functionScore:
    boost_mode: multiply
    functions:
    - filter:
        term:
          hasActiveIncidents:
            value: true
      weight: 2
    - filter:
        term:
          hasDescription:
            value: true
      weight: 1.25
    - filter:
        term:
          hasOwners:
            value: true
      weight: 1.25
    - filter:
        term:
          hasDomain:
            value: true
      weight: 1.1
    - filter:
        term:
          hasGlossaryTerms:
            value: true
      weight: 1.1
    - filter:
        term:
          hasTags:
            value: true
      weight: 1.1
    - filter:
        term:
          hasRowCount:
            value: true
      weight: 1.05
    - filter:
        term:
          hasColumnCount:
            value: true
      weight: 1.05
    - filter:
        term:
          deprecated:
            value: true
      weight: 0.5
    score_mode: multiply
  prefixMatchQuery: false
  queryRegex: '[*]|'
  simpleQuery: false
- exactMatchQuery: true
  functionScore:
    boost_mode: multiply
    functions:
    - filter:
        term:
          deprecated:
            value: true
      weight: 0.5
    score_mode: multiply
  prefixMatchQuery: true
  queryRegex: ^[a-zA-Z0-9]\S+[_.-]\S+[a-zA-Z0-9]$
  simpleQuery: false
- exactMatchQuery: true
  functionScore:
    boost_mode: multiply
    functions:
    - filter:
        term:
          deprecated:
            value: true
      weight: 0.5
    score_mode: multiply
  prefixMatchQuery: true
  queryRegex: ^["'].+["']$
  simpleQuery: false
- exactMatchQuery: true
  functionScore:
    boost_mode: multiply
    functions:
    - filter:
        prefix:
          urn:
            value: 'urn:li:container:'
      weight: 5
    score_mode: multiply
  prefixMatchQuery: true
  queryRegex: .*
  simpleQuery: true
```

**To Reproduce**
Steps to reproduce the behaviour:

- When running the following simplified graphql query in the UI:
```
  $filters: [AndFilterInput!]
  $sort: SearchSortInput
) {
  searchAcrossEntities(
    input: {
      types: $types
      query: $query
      start: $start
      count: $count
      orFilters: $filters
      sortInput: $sort
    }
  ) {
    start
    count
    total
    searchResults {
      entity {
        type
        urn
      }
    }
  }
}
```

- With the following vars:

```
{
  "count": 3000,
  "query": "offence",
  "start": 0,
  "types": [
    "CONTAINER",
    "DATASET",
    "CHART",
    "DASHBOARD"
  ],
  "filters": [
    {
      "and": [
        {
          "field": "tags",
          "values": [
            "urn:li:tag:dc_display_in_catalogue"
          ]
        }
      ]
    }
  ]
}
```

We receive the following results. Containers are present in the results but are not prioritised / boosted i.e. at the top. The results still show DATASETS at the top.

```
{
  "data": {
    "searchAcrossEntities": {
      "start": 0,
      "count": 3000,
      "total": 321,
      "searchResults": [
        {
          "entity": {
            "type": "DATASET",
            "urn": "urn:li:dataset:(urn:li:dataPlatform:glue,xhibit_preprocessed.offence,PROD)"
          }
        },
        {
          "entity": {
            "type": "DATASET",
            "urn": "urn:li:dataset:(urn:li:dataPlatform:dbt,cadet.awsdatacatalog.crest_v1_dev.offence,PROD)"
          }
        },
        {
          "entity": {
            "type": "DATASET",
            "urn": "urn:li:dataset:(urn:li:dataPlatform:glue,common_platform_dev_sdp_v3.offence_detail,PROD)"
          }
        },
     < Results omitted >
     ]
   }
}
```
- If i run the same Graphql query and restrict `"types": ["CONTAINER"]`, 12 container entities are returned.
```{
  "data": {
    "searchAcrossEntities": {
      "start": 0,
      "count": 3000,
      "total": 12,
      "searchResults": [
        {
          "entity": {
            "type": "CONTAINER",
            "urn": "urn:li:container:ec32475a2e01d6108a241ad201811f24"
          }
        },
        {
          "entity": {
            "type": "CONTAINER",
            "urn": "urn:li:container:ecd3f76bfcdc998b62a4ea750534d5bf"
          }
        },
       < Results omitted >
      ]
    }
  },
  "extensions": {}
}
```

```
{
  "count": 3000,
  "query": "offence",
  "start": 0,
  "types": [
    "CONTAINER"
  ],
  "filters": [
    {
      "and": [
        {
          "field": "tags",
          "values": [
            "urn:li:tag:dc_display_in_catalogue"
          ]
        }
      ]
    }
  ]
}
```
- GMS Debug Logs

[Front End Search (with Facets).txt](https://github.com/user-attachments/files/20759907/Front.End.Search.with.Facets.txt)

[Graphql search](https://github.com/user-attachments/files/20759927/Graphql.search.gms.logs.txt)
