### ISSUE TITLE
Quickstart ingest from Oracle DB fails from UI but works from CLI

### ISSUE THREAD

**Issue by mw-mec** [datahub-project/datahub#13817]
**Describe the bug**
Using the docker quickstart, the same config for extracting from Oracle DB fails in the UI but succeeds from the CLI.

**To Reproduce**
Run `datahub docker quickstart` and sign in as default user
In UI, add data source with the following config (values changed for privacy):

```
source:
    type: oracle
    config:
        host_port: 'host.domain:12345'
        username: MY_USER
        password: 'mypassword'
        service_name: myservice.name
        enable_thick_mode: true
sink:
    type: datahub-rest
    config:
        server: 'http://x.x.x.x:8080'

```

Save and run. Note the following error in the logs:
`Failed to configure the source (oracle): 1 validation error for OracleConfig
enable_thick_mode
  extra fields not permitted (type=value_error.extra)`

This same config runs from the CLI without error. 

If I omit the thick mode parameter. I receive the following, so it seems thick mode is required. 

`<class 'sqlalchemy.exc.OperationalError'>: (oracledb.exceptions.OperationalError) DPY-6005: cannot connect to database (CONNECTION_ID=GjI7f2+plaqsFPbVdIHyDA==).
DPY-3001: Native Network Encryption and Data Integrity is only supported in python-oracledb thick mode
(Background on this error at: https://sqlalche.me/e/14/e3q8)`

**Expected behavior**
Data is ingested
