### ISSUE TITLE
Sensitive values in Kafka sink config written to logs

### ISSUE THREAD

**Issue by jameslamb** [datahub-project/datahub#2878]
**Describe the bug**

When using `datahub ingest` to ingest Looker metadata, I noticed that an INFO-level log message is emitted which logs out sensitive information in plain text.

> [2021-07-14 14:46:47,746] INFO     {datahub.entrypoints:74} - Using config: {'source': {'type': 'lookml', 'config': {'base_folder': '/model-files', 'connection_to_platform_map': {'redshift_test': 'redshift', 'presto': 'presto'}, 'platform_name': 'looker', 'env': 'PROD', 'parse_table_names_from_sql': False}}, 'sink': {'type': 'datahub-kafka', 'config': {'connection': {'bootstrap': 'REDACTED', 'producer_config': {'security.protocol': 'SSL', 'ssl.ca.location': '/etc/service/keys/ca', 'ssl.certificate.location': '/etc/service/keys/cert', 'ssl.key.location': '/etc/service/keys/key'}, 'schema_registry_url': 'REDACTED', 'schema_registry_config': {'basic.auth.user.info': 'REDACTED'}}}}}

I manually added the `REDACTED` pieces above. I think the `schema_registry_url` should be obscured before writing that log message (since it can contain a password), and that `basic.auth.user.info` should also be obscured (since, if provided, it contains a username and password for the Kafka cluster).

**To Reproduce**

Using `acryl-datahub[lookml, datahub-kafka]==0.8.5`, I'm ingesting Looker metadata extracted from LookML model files, following https://datahubproject.io/docs/metadata-ingestion/#lookml-lookml.

```shell
datahub ingest -c recipes/recipe.yaml
```

With `recipe.yaml` that looks like this.

```yaml
source:
  type: lookml
  config:
    base_folder: /lookml-model-files
    connection_to_platform_map:
      presto: presto
    platform_name: looker
    env: "PROD"
    parse_table_names_from_sql: False

sink:
  type: "datahub-kafka"
  config:
    connection:
      bootstrap: "${KAFKA_BOOTSTRAP_SERVER}"
      producer_config:
        security.protocol: SSL
        ssl.ca.location: /etc/service/keys/ca
        ssl.certificate.location: /etc/service/keys/cert
        ssl.key.location: /etc/service/keys/key
      schema_registry_url: "${KAFKA_SCHEMA_REGISTRY_URL}"
      schema_registry_config:
        basic.auth.user.info: "${KAFKA_SCHEMA_REGISTRY_USER}:${KAFKA_SCHEMA_REGISTRY_PW}"
```

**Expected behavior**

I expected that sensitive information like passwords would not be logged.

**Screenshots**

None

**Desktop (please complete the following information):**

I'm running `datahub ingest` in a container using the `python:3.7-slim` image.

**Additional context**

I did look in https://github.com/linkedin/datahub/blob/a6dc9e0dc0946bcc8f6bdcb6878520581fe05616/metadata-ingestion/src/datahub/ingestion/source/lookml.py but don't see any `logger.info()` calls there, so I expect that logging the recipe contents is happening somewhere further upstream in the codebase. That might mean that this issue affects more than just LookML ingestion.

Thanks for your time and consideration.
