### ISSUE TITLE
MySQL ingestion bringing all schemas in server, despite declaration of database in recipe

### ISSUE THREAD

**Issue by txicos** [datahub-project/datahub#3204]
**Describe the bug**
mysql recipe to ingest mydatabase schema into datahub, bringing the schemas of all databases in myserver, instead of just the ones present in mydatabase.

```
---
# see https://datahubproject.io/docs/metadata-ingestion/source_docs/mysql for complete documentation
source:
  type: "mysql"
  config:
    username: my.user
    password: 12345678
    host_port: myserver.com:21286
    database: mydatabase

# see https://datahubproject.io/docs/metadata-ingestion/sink_docs/datahub for complete documentation
sink:
  type: "datahub-rest"
  config:
    server: "http://localhost:8080"
```

**To Reproduce**
1. Use above mysql recipe as template to ingest metadata into DataHub and name it mysqlrecipe.yml
2. Run `datahub ingest -c mysqlrecipe.yml`
3. Check in command line log that all databases  in myserver are being ingested instead of just mydatabase

**Expected behavior**
Only the table schemas present in mydatabase should be ingested.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Unbuntu 20.04
 - Browser: firefox 91.0.2
 - Version: acryl-datahub, version 0.8.11.0

**Additional context**
It is possible that all databases are being returned because of this code [sql_common.py](https://github.com/linkedin/datahub/blob/9b81fa428cfa10260b047c6656180f1d90a33978/metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py#L293)

```
def get_schema_names(self, inspector):
        return inspector.get_schema_names()
```

The `get_schema_names()` method always returns all available schemas in server no matter you selected a default schema.
A possible solution could be:
```
def get_schema_names(self, inspector):
    if inspector.default_schema_name is not None:
        return [inspector.default_schema_name]
    else:
        return inspector.get_schema_names()
```
