### ISSUE TITLE
Ingestion stack trace leaks credentials (at least Mongo source)

### ISSUE THREAD

**Issue by frsann** [datahub-project/datahub#3645]
**Describe the bug**
The stack trace of a failed ingestion job (at least using the MongoDB source) leaks credentials. 

**To Reproduce**
1. Spin up a MongoDB instance using docker (This step might not be needed)
2. Create a Mongo ingestion recipe with wrong credentials. (My assumption is that other conditions could trigger the same behavior, like temporary connection drop) 
```yaml
source:
  type: "mongodb"
  config:
    # Coordinates
    connect_uri: mongodb://localhost:27017

    # Credentials
    username: bob
    password: pass
    authMechanism: "DEFAULT"

    # Options
    enableSchemaInference: True
    useRandomSampling: True
    schemaSamplingSize: 50

sink:
  type: "file"
  config:
    filename: output.json
```
3. Run the recipe and capture the stdout/stderr in a file. 
4. Check the logs.

In my case the logs included this like this:
```
[2021-11-30 21:11:56,850] ERROR    {datahub.entrypoints:101} - File "/home/fredrik/miniconda3/envs/datahub-dev/lib/python3.8/site-packages/pymongo/pool.py", line 1278, in _get_socket
    1246  def _get_socket(self, all_credentials):
 (...)
    1274  
    1275          while sock_info is None:
    1276              try:
    1277                  with self.lock:
--> 1278                      sock_info = self.sockets.popleft()
    1279              except IndexError:
    ..................................................
     self = <pymongo.pool.Pool object at 0x7f62dbaf76a0>
     all_credentials = {'admin': MongoCredential ('DEFAULT', 'admin', 'bob', 'pass', None, <pymongo.auth._Cache object at 0x7f62dbaf7070>, )}
     sock_info = None
     self.lock = <unlocked _thread.lock object at 0x7f62dbaf7ab0>
    ..................................................

IndexError: pop from an empty deque
```
```
     config = PipelineConfig(source=SourceConfig(type='mongodb', config={'connect_uri': 'mongodb://localhost:27017', 'username': 'bob'
               , 'password': 'pass', 'authMechanism': 'DEFAULT', 'enableSchemaInference': True, 'useRandomSampling': True, 'schemaSampl
               ingSize': 50}, extractor='generic'), sink=DynamicTypedConfig(type='file', config={'filename': 'output.json'}), transform
               ers=None, run_id='mongodb-2021_11_30-21_11_56', datahub_api=None)
```
```
     all_credentials = {'admin': MongoCredential ('DEFAULT', 'admin', 'bob', 'pass', None, <pymongo.auth._Cache object at 0x7f62dbaf7070>, )}
```
So it seems it's leaking from both Datahub `metadata-ingestion` and `pymongo` .

**Expected behavior**
The logs do not contain sensitive info.
