### ISSUE TITLE
Error when installing ALB ingress for datahub frontend

### ISSUE THREAD

**Issue by hugh-nguyen** [datahub-project/datahub#4495]
**Describe the bug**
I'm following the guide to setting up DataHub on AWS
https://datahubproject.io/docs/deploy/aws

I've gotten to the stage where I need to update values.yaml to in order to attach the ALB ingress to the frontend.

It looks like this - 
```
datahub-frontend:
  enabled: true
  image:
    repository: linkedin/datahub-frontend-react
    tag: "latest"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: instance
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-2:601628467906:certificate/xxxxxx
      alb.ingress.kubernetes.io/inbound-cidrs: 0.0.0.0/0
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    hosts:
      - host: xxxx
        redirectPaths:
          - path: /*
            name: ssl-redirect
            port: use-annotation
        paths:
          - /*
 ```

When I run the upgrade however I am getting the following error.
```
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0].backend.service.port.number): invalid type for io.k8s.api.networking.v1.ServiceBackendPort.number: got "string", expected "integer"
```

**Expected behavior**
Successful Upgrade

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser None
 - Version latest

**Additional context**
ALB seems to there, and site is reachable when using port forwarding for local access
