### ISSUE TITLE
Clickhouse ingestion error

### ISSUE THREAD

**Issue by Plozano94** [datahub-project/datahub#4506]
**Describe the bug**
We are trying to test the new clickhosue ingestion feature trying to fetch metadata from clickhouse through de UI. Error:            "KeyError: 'Did not find a registered class for clickhouse'\n".

Earlier in the log, I don't know why in the worker is trying to install wrong version of acryl-datahub:

```
            'Collecting acryl-datahub[clickhouse,datahub-rest]==0.8.26.6\n'
           '  Using cached acryl_datahub-0.8.26.6-py3-none-any.whl (607 kB)\n'
           "WARNING: acryl-datahub 0.8.26.6 does not provide the extra 'clickhouse'\n"
```
when we have installed 0.8.31.3.

**To Reproduce**
1. datahub docker nuke --keep-data
2. python3.9 -m pip install --upgrade acryl-datahub (our version is  version 0.8.31.3)
3. datahub docker quickstart --quickstart-compose-file docker-compose-without-neo4j.quickstart.yml (modified yml version including metadata auth env variable )
4. Log in -> Ingestion -> create new source -> Custom ->
```
source:
    type: clickhouse
    config:
        host_port: '...'
        username: ...
        password: '...'
        database: ....
sink:
    type: datahub-rest
    config:
        server: '...'
        token: ...
```
 (replace ... with values in each case)

5. Execute

**Expected behavior**
Ingestion correctly done

**Screenshots**
Atached full log

**Desktop (please complete the following information):**
 -   SMP Debian 4.9.303-1 (2022-03-07) x86_64 GNU/Linux

[datahub-ingestion.log](https://github.com/datahub-project/datahub/files/8362069/datahub-ingestion.log)

Thanks in advance!
.
