### ISSUE TITLE
BigQuery Lineage: not possible to read entries from exported audit metadata

### ISSUE THREAD

**Issue by vgaidass** [datahub-project/datahub#4529]
**Describe the bug**
Ingestion of BigQuery recipe with `use_exported_bigquery_audit_metadata: true` fails at "Unable to parse audit metadata missing timestamp" while there is definitely a timestamp field present:
![image](https://user-images.githubusercontent.com/14344344/160780552-c3c29c30-9bac-421c-84a6-f421f1dc5081.png)

**To Reproduce**
1. Have acryl-datahub of version **0.8.31.6 EDIT: or 0.8.32** (seems like every version >0.8.31 is affected)
2. Have exported audit metadata table in place in BigQuery:
![image](https://user-images.githubusercontent.com/14344344/160771572-2ef2f062-d1f1-4c20-8cb4-04d4b4f0251d.png)

3. datahub docker quickstart
4. Recipe:
```
source:
  type: bigquery
  config:
    # Coordinates
    project_id: "${GCP_PROJECT}"
    ## Credentials
    credential:
      project_id: "${GCP_PROJECT}"
      private_key_id: "foo"
      private_key: "foo"
      client_email: "foo"
      client_id: "foo"
    use_exported_bigquery_audit_metadata: true
    bigquery_audit_metadata_datasets: [
      "${GCP_PROJECT}.${DATASET_WITH_EXPORTED_AUDIT_METADATA}"
    ]
    start_time: "2022-03-01T00:00:00Z"
    end_time: "2050-01-01T00:00:00Z"
sink:
  type: "datahub-rest"
  config:
    server: "http://localhost:8080"
```
5. datahub ingest -c <RECIPE_ADDRESS>

**Expected behavior**
Exported audit metadata is being processed and pushed further to DataHub REST.

**Additional context**
After some debugging on my own, I believe that the issue is with the method `get_first_missing_key_any()` (created at #4442 ) at `datahub.utilities.parsing_util` that is being called at `get_missing_key_exported_bigquery_audit_metadata()` at `datahub.ingestion.source_report.usage.bigquery_usage`
* The method expects a dict type from the BQ client `query()` method that comes from `_get_exported_bigquery_audit_metadata()` but it arrives as Row() type:
![image](https://user-images.githubusercontent.com/14344344/160783508-8d246cc9-3c36-4558-818b-032d8b683e3c.png)
* The method tries to look for values of `keys` but fails to do so
* Possible fix: give `row._xxx_field_to_index` to `get_first_missing_key_any()` instead of `row`. Not sure if other sources are to be affected by the change
