### ISSUE TITLE
Memory leak when using DataHub Action for Great Expectations

### ISSUE THREAD

**Issue by oyarushe** [datahub-project/datahub#4531]
**Describe the bug**
I'm running the Great Expectations task in Apache Airflow using Docker.
When I added the great_expectations action to ingest validation data to DataHub, my task failed with a memory leak.
Logs:
```
[2022-03-30, 11:20:37 UTC] {great_expectations.py:80} INFO - Running validation with Great Expectations...
[2022-03-30, 11:20:37 UTC] {great_expectations.py:83} INFO - Ensuring data context is valid...
[2022-03-30, 11:20:37 UTC] {data_context.py:620} INFO - Usage statistics is disabled; skipping initialization.
[2022-03-30, 11:20:58 UTC] {local_task_job.py:154} INFO - Task exited with return code Negsignal.SIGKILL
[2022-03-30, 11:20:58 UTC] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=dwh_process_dim_tables, task_id=ge_dim_truck, execution_date=20220329T000000, start_date=20220330T112036, end_date=20220330T112058
[2022-03-30, 11:20:58 UTC] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
```
Action configuration:
```
  - name: datahub_action
    action:
      module_name: datahub.integrations.great_expectations.action
      class_name: DataHubValidationAction
      server_url: http://datahub-gms:8080/
```
Screen from Docker stats:
![image](https://user-images.githubusercontent.com/33004847/160831854-d445a853-df40-4923-a899-db06ca26ffd4.png)

Do you have any idea what can be the problem?

**To Reproduce**
1. Run Apache Airflow in Docker
2. Create a task using GreatExpectationsOperator
3. Run task

**Expected behavior**
Validation data ingested to DataHub.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
