### ISSUE TITLE
The extended data model was not recognized

### ISSUE THREAD

**Issue by Huyueeer** [datahub-project/datahub#4617]
I confirm the extended data model under `metadata-models-custom` package according to the information given in the document:
1. Create PDL file and write in `entity-registry.yaml` file
```yaml
id: kbase-model
entities:
  - name: glossaryTerm
    keyAspect: glossaryTermKey
    aspects:
      - kbaseSchemaMetadata
```
2. Then package the project and get the zip in `dist`;
3. Because we are a docker deployment project, I manually unzip the zip package to get `libs` and `entity-registry.yaml` . which are placed in the `/etc/datahub/plugins/models/kbase-model/0.0.1/`directory mapped by docker.
4. The log also outputs the log about this aspect, but there is no query under `/config`
![image](https://user-images.githubusercontent.com/40758588/162345621-0065f4a8-b92f-4045-997a-eef67d1c445d.png)
```shell
curl -s http://localhost:8080/config | jq .
{
  "supportsImpactAnalysis": true,
  "models": {},
  "versions": {
    "linkedin/datahub": {
      "version": "v0.8.28",
      "commit": "beb51ebf59a045de0aac9115f6eeecc8f7207d6b"
    }
  },
  "statefulIngestionCapable": true,
  "retention": "true",
  "noCode": "true"
}
```
