### ISSUE TITLE
UI ingestion for kafka-connect lacks of java

### ISSUE THREAD

**Issue by KulykDmytro** [datahub-project/datahub#4741]
**Describe the bug**
There is no correctly set up Java in Action container (UI ingestion) to process `kafka-connect` source

**To Reproduce**
1. Open UI ingestion
2. create source config for `kafka-connect`
3. execute ingestion
4. observe error

**Expected behavior**

**Screenshots**
```yaml
source:
  type: kafka-connect
  config:
    connect_uri: 'http://kafka-connect.confluent.svc.cluster.local:8083'
    cluster_name: dwh-connect
    connector_patterns:
      allow:
        - '^dwh-.*'
sink:
  type: datahub-rest
  config:
    server: 'http://datahub-datahub-gms:8080'
    token: xxxxx

```
Error
```verilog
JVMNotFoundException: No JVM shared library file (libjvm.so) found. Try setting up the JAVA_HOME environment variable properly.
```

**Environment:**
 - EKS 1.22
 - official chart
 - core version: 0.8.33
 - chart version: 0.2.69
