### ISSUE TITLE
Failed to configure MYSQL Source in Manage Ingestion module

### ISSUE THREAD

**Issue by Su1024** [datahub-project/datahub#4873]
**Describe the bug**
Failed to configure MYSQL Source in Manage Ingestion module
<img width="688" alt="image" src="https://user-images.githubusercontent.com/23012179/167251435-dde4839f-f788-42ed-adc8-be588d399899.png">
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/23012179/167251451-1216789d-7dc4-4ccc-b79b-cd746e6cf413.png">

**Comment by shirshanka** [comment]
Looks like you've fallen into the common trap of connecting to `localhost:9002` from the docker container, which doesn't work. 
If you replace the sink section with 
```
sink:
   type: "datahub-rest"
   config:
       server: "http://datahub-gms:8080"

```

it should fix itself. 


We are working to remove this common pitfall soon 🙏
