### ISSUE TITLE
Datahub GMS service unable to connect with secured elasticsearch instance 

### ISSUE THREAD

**Issue by nj7** [datahub-project/datahub#5046]
**Describe the bug**
Datahub-GMS service is unable to connect with elastic search instance that has security enabled.
If elastic search ```xpack.security.enabled=true``` is enabled then datahub-gms service fails at `UpdateIndicesHooks`  and throws below error
```
Caused by: 
org.elasticsearch.client.ResponseException: method [HEAD], host [http://elasticsearch:9200], URI [/graph_service_v1?ignore_throttled=false&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=false], status line [HTTP/1.1 401 Unauthorized]
```

**To Reproduce**
Just use the docker configuration below to reproduce 
```
networks:
  default:
    name: datahub_network
services:
  broker:
    container_name: broker
    depends_on:
    - zookeeper
    environment:
    - KAFKA_BROKER_ID=1
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
    - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
    - KAFKA_HEAP_OPTS=-Xms256m -Xmx256m
    hostname: broker
    image: kymeric/cp-kafka:latest
    ports:
    - 29092:29092
    - 9092:9092
  datahub-actions:
    depends_on:
      - datahub-gms
    environment:
      - GMS_HOST=datahub-gms
      - GMS_PORT=8080
      - KAFKA_BOOTSTRAP_SERVER=broker:29092
      - SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - METADATA_AUDIT_EVENT_NAME=MetadataAuditEvent_v4
      - METADATA_CHANGE_LOG_VERSIONED_TOPIC_NAME=MetadataChangeLog_Versioned_v1
      - DATAHUB_SYSTEM_CLIENT_ID=__datahub_system
      - DATAHUB_SYSTEM_CLIENT_SECRET=JohnSnowKnowsNothing
      - KAFKA_PROPERTIES_SECURITY_PROTOCOL=PLAINTEXT
    hostname: actions
    image: acryldata/datahub-actions:${ACTIONS_VERSION:-head}
    restart: on-failure:5
  datahub-frontend-react:
    container_name: datahub-frontend-react
    depends_on:
    - datahub-gms
    environment:
    - DATAHUB_GMS_HOST=datahub-gms
    - DATAHUB_GMS_PORT=8080
    - DATAHUB_SECRET=YouKnowNothing
    - DATAHUB_APP_VERSION=1.0
    - DATAHUB_PLAY_MEM_BUFFER_SIZE=10MB
    - JAVA_OPTS=-Xms512m -Xmx512m -Dhttp.port=9002 -Dconfig.file=datahub-frontend/conf/application.conf
      -Djava.security.auth.login.config=datahub-frontend/conf/jaas.conf -Dlogback.configurationFile=datahub-frontend/conf/logback.xml
      -Dlogback.debug=false -Dpidfile.path=/dev/null
    - KAFKA_BOOTSTRAP_SERVER=broker:29092
    - DATAHUB_TRACKING_TOPIC=DataHubUsageEvent_v1
    - ELASTIC_CLIENT_HOST=elasticsearch
    - ELASTIC_CLIENT_PORT=9200
    - ELASTIC_CLIENT_USERNAME=elastic
    - ELASTIC_CLIENT_PASSWORD=DkIedPPSCb
    hostname: datahub-frontend-react
    image: linkedin/datahub-frontend-react:${DATAHUB_VERSION:-head}
    ports:
    - 9002:9002
    volumes:
      - ${HOME}/.datahub/plugins:/etc/datahub/plugins
  datahub-gms:
    container_name: datahub-gms
    depends_on:
    - mysql
    environment:
    - METADATA_SERVICE_AUTH_ENABLED=true
    - DATASET_ENABLE_SCSI=false
    - EBEAN_DATASOURCE_USERNAME=datahub
    - EBEAN_DATASOURCE_PASSWORD=datahub
    - EBEAN_DATASOURCE_HOST=mysql:3306
    - EBEAN_DATASOURCE_URL=jdbc:mysql://mysql:3306/datahub?verifyServerCertificate=false&useSSL=true&useUnicode=yes&characterEncoding=UTF-8
    - EBEAN_DATASOURCE_DRIVER=com.mysql.jdbc.Driver
    - KAFKA_BOOTSTRAP_SERVER=broker:29092
    - KAFKA_SCHEMAREGISTRY_URL=http://schema-registry:8081
    - ELASTICSEARCH_HOST=elasticsearch
    - ELASTICSEARCH_PORT=9200
    - ELASTICSEARCH_USERNAME=elastic
    - ELASTICSEARCH_PASSWORD=DkIedPPSCb
    - GRAPH_SERVICE_IMPL=elasticsearch
    - JAVA_OPTS=-Xms1g -Xmx1g
    - ENTITY_REGISTRY_CONFIG_PATH=/datahub/datahub-gms/resources/entity-registry.yml
    - MAE_CONSUMER_ENABLED=true
    - MCE_CONSUMER_ENABLED=true
    - DATAHUB_TELEMETRY_ENABLED=${DATAHUB_TELEMETRY_ENABLED:-true}
    - PE_CONSUMER_ENABLED=true
    hostname: datahub-gms
    image: linkedin/datahub-gms:${DATAHUB_VERSION:-head}
    ports:
    - 8080:8080
    volumes:
    - ${HOME}/.datahub/plugins:/etc/datahub/plugins
  elasticsearch:
    container_name: elasticsearch
    environment:
    - ELASTIC_PASSWORD=DkIedPPSCb
    - discovery.type=single-node
    - xpack.security.enabled=true
    - ES_JAVA_OPTS=-Xms256m -Xmx256m -Dlog4j2.formatMsgNoLookups=true
    hostname: elasticsearch
    image: elasticsearch:7.16.2
    mem_limit: 1g
    ports:
    - 9200:9200
    volumes:
    - esdata:/usr/share/elasticsearch/data
  elasticsearch-setup:
    container_name: elasticsearch-setup
    depends_on:
    - elasticsearch
    environment:
    - ELASTICSEARCH_USERNAME=elastic
    - ELASTICSEARCH_PASSWORD=DkIedPPSCb
    - ELASTICSEARCH_HOST=elasticsearch
    - ELASTICSEARCH_PORT=9200
    - ELASTICSEARCH_PROTOCOL=http
    hostname: elasticsearch-setup
    image: linkedin/datahub-elasticsearch-setup:${DATAHUB_VERSION:-head}
  kafka-setup:
    container_name: kafka-setup
    depends_on:
    - broker
    - schema-registry
    environment:
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_BOOTSTRAP_SERVER=broker:29092
    hostname: kafka-setup
    image: linkedin/datahub-kafka-setup:${DATAHUB_VERSION:-head}
  mysql:
    container_name: mysql
    hostname: mysql
    image: mariadb:10.5.8
    env_file: mysql/env/docker.env
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysqldata:/var/lib/mysql

  mysql-setup:
    build:
      context: ../
      dockerfile: docker/mysql-setup/Dockerfile
    image: acryldata/datahub-mysql-setup:head
    env_file: mysql-setup/env/docker.env
    hostname: mysql-setup
    container_name: mysql-setup
    depends_on:
      - mysql
  schema-registry:
    container_name: schema-registry
    depends_on:
    - zookeeper
    - broker
    environment:
    - SCHEMA_REGISTRY_HOST_NAME=schemaregistry
    - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
    hostname: schema-registry
    image: eugenetea/schema-registry-arm64:latest
    ports:
    - 8081:8081
  zookeeper:
    container_name: zookeeper
    environment:
    - ZOOKEEPER_CLIENT_PORT=2181
    - ZOOKEEPER_TICK_TIME=2000
    hostname: zookeeper
    image: kymeric/cp-zookeeper:latest
    ports:
    - 2181:2181
    volumes:
    - zkdata:/var/opt/zookeeper
version: '2.3'
volumes:
  esdata: null
  mysqldata: null
  zkdata: null
```

**Expected behavior**
Should be able to connect with elastic search seamlessly with or without authentication enabled 

**Desktop (please complete the following information):**
 - OS: OS independent 
 - Browser independent
 - Version v0.8.35
