### ISSUE TITLE
Cannot use 'datahub-kafka' sink with UI ingestion on Kubernetes

### ISSUE THREAD

**Issue by jflowgh** [datahub-project/datahub#5170]
**Describe the bug**
When I try to run a metadata ingest job through the frontend UI with `datahub-kafka` as the sink I get a pip error that it's disabled. The [UI ingestion docs](https://datahubproject.io/docs/ui-ingestion#step-1-select-a-platform-template) say that `datahub-rest` or `datahub-kafka` should work by default.
Installed Datahub via the [Kubernetes Helm charts](https://datahubproject.io/docs/deploy/kubernetes/).

**To Reproduce**
1. Install Datahub via [Kubernetes Helm charts](https://datahubproject.io/docs/deploy/kubernetes/)
2. Login, go to "Ingestion" tab
3. Create a custom source with a sink like:
```
sink:
    type: datahub-kafka
    config:
        connection:
            bootstrap: 'prerequisites-kafka:9092'
            schema_registry_url: 'http://prerequisites-cp-schema-registry:8081'
```
4. Execute ingestion job
5. Get back error:
```
'[2022-06-14 16:47:28,288] INFO     {datahub.cli.ingest_cli:97} - DataHub CLI version: 0.8.36\n'
'[2022-06-14 16:47:28,347] ERROR    {datahub.entrypoints:165} - datahub-kafka is disabled; try running: pip install '
 "'acryl-datahub[datahub-kafka]'\n"
```

**Expected behavior**
`datahub-kafka` sink should work and ingestion should run.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser FF
 - Version: 101.0.1

**Additional context**
Is it possible for me to bake in that `acryl-datahub[datahub-kafka]` package to an image, or to update the `pip install` requirements.txt it's using for these jobs somehow? I don't see any options through the helm chart ATM.
