### ISSUE TITLE
No able to connect to postgres using Datahub

### ISSUE THREAD

**Issue by Kuladeep1996** [datahub-project/datahub#5258]
**Describe the bug**
We're trying to connect to postgres using localhost on datahub but its failing due to following error
"ConnectionError: HTTPConnectionPool(host='datahub-gms', port=8080): Max retries exceeded with url: /config (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FA948EE020>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"

**To Reproduce**
1. Create yml file to ingest data from postgres
2. Run manually either from UI or using cmd

**Expected behavior**
load metadata from postgres to datahub

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome
 - Version : 103.0.5060.53

**Comment by treff7es** [comment]
It seems like your local DataHub is not running or the machine where you run the ingestion is unable to access.
`HTTPConnectionPool(host='datahub-gms', port=8080)`

**Comment by Kuladeep1996** [comment]
checked status of GMS container and its healthy 
![image](https://user-images.githubusercontent.com/74226018/176415760-8ca467cf-6e6d-48d2-9f3d-656c24c22ff6.png)

We tried to do ingestion using oracle DB and it ran successfully. Only postgres we are getting this issue

**Comment by pedro93** [comment]
Is Postgres running in the same place as Oracle CB?
Could provide more details as to where and how Postgres was deployed?

**Comment by pedro93** [comment]
Oracle recipe does not have a sink? Do you see Oracle data in DataHub UI?
Does Postgres ingestion _finish_ successfully if you remove the sink config?

**Comment by Kuladeep1996** [comment]
in one of the doc it mentioned as no need to keep sink it'll automatically take Datahub Ui as default.
It even ingested metadata for oracle without sink
![image](https://user-images.githubusercontent.com/74226018/176418874-31604c8d-b75c-4e71-a84c-ffa24dbcd4e7.png)

For postgres its failing due to this issue 
"ConnectionError: HTTPConnectionPool(host='datahub-gms', port=8080): Max retries exceeded with url: /config (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FA948EE020>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"

**Comment by pedro93** [comment]
What is the output of `datahub ingest -c postgres.yml` where `postgres.yml` has the following content:
```
source:
    type: "postgres"
    config:
        host_port: "localhost:5432"
        database: "employee"
        username: "postgres"
        password: "*******"
        include_tables: true
        include_views: true
        profiling:
            enabled: false
```

?

**Comment by Kuladeep1996** [comment]
![image](https://user-images.githubusercontent.com/74226018/176424150-4a1a02e0-ec4a-48f8-a0a0-0a3051a95a1b.png)

**Comment by Kuladeep1996** [comment]
hey if i keep sink in yml file then im getting connection error..
Now i tried by removing sink for postgres also and load was successful
![image](https://user-images.githubusercontent.com/74226018/176428941-85b2a06f-8106-49bb-b3a2-56960472c4cc.png)

**Comment by pedro93** [comment]
That is because your sink is incorrectly configured.
```
sink:
    type: "datahub-rest"
    config:
        server: 'http://datahub-gms:8080'
```
It should be pointing to `localhost:8080` not `datahub-gms:8080` because your ingestion is running out side of docker.
https://datahubproject.io/docs/metadata-ingestion/sink_docs/datahub#quickstart-recipe
