### ISSUE TITLE
Korean is not included in metadata

### ISSUE THREAD

**Issue by rlatjgml38** [datahub-project/datahub#5325]
**Describe the bug**
When I try to input Korean in description an error occurs.
I think I need utf8 encoding to input Korean. What should I do?

**To Reproduce**
1. Made the json file (test3.json)
```
[
{
    "auditHeader": null,
    "entityType": "dataset",
    "entityUrn": "urn:li:dataset:(urn:li:dataPlatform:oracle,한글테스트2,PROD)",
    "entityKeyAspect": null,
    "changeType": "UPSERT",
    "aspectName": "datasetProperties",
    "aspect": {
        "value": "{\"description\": \"한글 설명\"}",
        "contentType": "application/json"
    },
    "systemMetadata": null
}
]
```
2. Made the yml file (file_to_datahub.yml)

```
source:
        type: "file"
        config:
                filename: "./test3.json"
sink:
        type: "datahub-rest"
        config:
                server: "http://localhost:8080"
reporting:
        - type: "datahub"
          config:
                  datahub_api:
                          server: "http://localhost:8080"
```
3. Run 
`datahub ingest -c file_to_datahub.yml`

**Screenshots**
![image](https://user-images.githubusercontent.com/48019174/177069006-9a110c25-8851-4319-ad51-a2c97d6d0ac7.png)
![image](https://user-images.githubusercontent.com/48019174/177069053-f816d62c-1b5b-4d4f-8663-de0b19c974ab.png)
![image](https://user-images.githubusercontent.com/48019174/177069085-a099e2c4-d37c-4900-8baa-bcd3728a3529.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Datahub Version: 0.8.32

**Additional context**
I succeeded in putting Korean in urn. When there is no Korean in the description. 
![image](https://user-images.githubusercontent.com/48019174/177070210-ce18d6ec-f2cc-44c3-95f3-de93b7aea15b.png)
However, Korean is not included in metadata. (e.g. description, column name, subtype's typeName, etc.)
And I tried to install v0.8.36 and v0.8.39, but I couldn't use it with a red error window saying "Oops, an error occurred".
