### ISSUE TITLE
dbt: Insert only dbt assertions

### ISSUE THREAD

**Issue by Santhin** [datahub-project/datahub#5327]
**Describe the bug**
When doing ingestion with only assertions created from `dbt test` it's additionally ingesting metadata that is already in datahub

**To Reproduce**
1. Initial ingest
```yaml
source:
  type: "dbt"
  config:
    manifest_path: "target/manifest.json"
    catalog_path: "target/catalog.json"
    sources_path: "target/sources.json"
    test_results_path: "target/run_results.json"
    target_platform: "postgres" # e.g. bigquery/postgres/etc.

sink:
  type: "datahub-rest"
  config:
    server: "http://localhost:8080"
```
2. Ingestion with only assertions
```yaml
source:
  type: "dbt"
  config:
    # Coordinates
    manifest_path: "target/manifest.json"
    catalog_path: "target/catalog.json"
    test_results_path: "target/run_results.json"
    
    target_platform: "postgres" # e.g. bigquery/postgres/etc.
    node_type_pattern:
      allow:
        - test

sink:
  type: "datahub-rest"
  config:
    server: "http://localhost:8080"
```

**Expected behavior**
With using `node_type_pattern` I'm getting `records_written': 18` but it should be `records_written': 6`

**Screenshots**
![image](https://user-images.githubusercontent.com/58829617/177115054-e9361681-e301-4fa9-9c87-3b278813b53b.png)
![image](https://user-images.githubusercontent.com/58829617/177115138-ab41895c-1c92-4d1c-8519-1439c139b4ad.png)

**Desktop (please complete the following information):**

**Additional context**
The possibility to ingest only results of assertions in a repeatable manner rather than transferring additional data about assertions object that is already created in datahub would be neat and wouldn't send redundantly metadata.

Solution proposal:

- add flag `enable_only_assertions`
- add if statement to https://github.com/acryldata/datahub/blob/master/metadata-ingestion/src/datahub/ingestion/source/dbt.py#L1298 with flag
