### ISSUE TITLE
White screen while trying to enter validation tab

### ISSUE THREAD

**Issue by Santhin** [datahub-project/datahub#5345]
**Describe the bug**
I found that while entering to validation tab I'm getting white screen after ingesting metadata from dbt / datahub

**To Reproduce**
dbt jaffle_shop, postgres, datahub 

```bash
datahub ingest -c recipe_dbt.yaml
```

```yaml
source:
  type: "dbt"
  config:
    # Coordinates
    manifest_path: "./target/manifest.json"
    catalog_path: "./target/catalog.json"
    sources_path: "./target/sources.json"
    target_platform: "postgres"
    env: "TEST"
sink:
  type: "datahub-rest"
  config:
    server: "http://localhost:8080"

```
![datahub-ui-bug](https://user-images.githubusercontent.com/58829617/177576137-41eb8218-00d2-471a-a7cf-8e31552ce50c.gif)
