### ISSUE TITLE
S3 Delta Lake Ingestion

### ISSUE THREAD

**Issue by james-chan-riiid** [datahub-project/datahub#5392]
**Describe the bug**
Not able to ingest from S3 Delta Table

**To Reproduce**
1. Have S3 directory with snappy.parquet files as content
2. Ingest with the following yaml via UI or CLI
```
source:
    type: delta-lake
    config:
        base_path: 's3://my_bucket'
        relative_path: my_relative_path
        s3:
            aws_config:
                aws_access_key_id: xxxx
                aws_secret_access_key: xxxxx
                aws_region: us-west-2
sink:
    type: datahub-rest
    config:
        server: 'http://172.17.0.1:8080'
```

**Expected behavior**
Data is ingested

**Screenshots**
```
'PyDeltaTableError: Failed to load checkpoint: Failed to read checkpoint content: Failed to read S3 object content: Request ID: None '
           'Body: <?xml version="1.0" encoding="UTF-8"?>\n'
           '<Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. '
           'Please send all future requests to this '
           'endpoint.
```

**Desktop (please complete the following information):**
 - OS: Amazon Linux T2.Large
 - Browser Chrome
 - Version 103.0.5060.114

**Additional context**
I noticed people are experiencing similar [issues](https://github.com/delta-io/delta-rs/issues/559) with the delta-rs module when they don't pass in the correct s3 region to the [DeltaTable class](https://github.com/delta-io/delta-rs/blob/main/python/deltalake/table.py#L72-L93).  I went ahead experimented with this behavior in my local Jupyter Notebook.  I noticed when I pass in the correct region, my notebook will instantiate a DeltaTable object properly.  When I pass the wrong region, I get the exact same error as the one I get when ingesting with Datahub.  This leads me to believe that Datahub code is not handling aws region correctly.  I then dug into the [Datahub source code](https://github.com/datahub-project/datahub/blob/master/metadata-ingestion/src/datahub/ingestion/source/delta_lake/delta_lake_utils.py#L20-L21) a bit and realized that the read_delta_table method is missing the region parameter.   I believe that is the reason I am getting this failure.

[Slack Thread](https://datahubspace.slack.com/archives/CUMUWQU66/p1657560730606079).

I tried to make those changes myself but my Datahub wouldn't build correctly on Apple M1 chip 🙃
