### ISSUE TITLE
Duplicates in datasets

### ISSUE THREAD

**Issue by Santhin** [datahub-project/datahub#5401]
**Describe the bug**
While ingestion from dbt in datasets, there are duplicates showing table/ view from dbt and the same object from database in my example it's snowflake.

**To Reproduce**

1. datahub docker quickstart
2. Ingest data with recipe:
```yaml
source:
  type: "dbt"
  config:
    manifest_path: "./target/manifest.json"
    catalog_path: "./target/catalog.json"
    sources_path: "./target/sources.json"
    test_results_path: "./target/run_results.json"
    env: "TEST"
    target_platform: "snowflake"

transformers:
  - type: "simple_add_dataset_tags"
    config:
      tag_urns:
        - "urn:li:tag:Santhin"
  - type: "simple_add_dataset_ownership"
    config:
      owner_urns:
        - "urn:li:corpuser:Santhin"
      ownership_type: "PRODUCER"
  - type: "set_dataset_browse_path"
    config:
      replace_existing: True
      path_templates:
        - /DATASET_PARTS
sink:
  type: "datahub-rest"
  config:
    server: "http://localhost:8080"
```
3. Check Datasets
![datahub-issue-duplicates](https://user-images.githubusercontent.com/58829617/179184433-986d0535-9644-47aa-b81a-933891165399.gif)

**Expected behavior**
 It's possible to merge them to one object and add that this object coming from dbt and snowflake like it's done here:
![image](https://user-images.githubusercontent.com/58829617/179184786-6468ab1c-6ea5-4732-95b0-021d4feaad2f.png)
