### ISSUE TITLE
Incorrect domain name when assigning via pattern match in config

### ISSUE THREAD

**Issue by KulykDmytro** [datahub-project/datahub#5497]
**Describe the bug**
When domain is being assigned via pattern matching it being created with incorrect name equals to URN like `urn:li:domain:Marketing`
```yaml
...
    domain:
      Marketing:
        allow: [ adpool, sfmc, sfsc, salesforce, dextra, quints, pm_offers ]
...
```

**To Reproduce**
1. setup ingestion config with domain mapping section (f.e. for `glue`)
2. run ingestion
3. see incorrect Domain created and assigned

**Expected behavior**
Domain name should be equal to one defined in config

![image](https://user-images.githubusercontent.com/34435869/181208676-4140a70d-150b-4860-bb06-2813f09b075c.png)
