### ISSUE TITLE
disable_ssl_verification parameter not working with Rest Sink

### ISSUE THREAD

**Issue by igor-kramer** [datahub-project/datahub#5542]
In documentation we can see disable_ssl_verification parameter but it's not available
https://datahubproject.io/docs/metadata-ingestion/sink_docs/datahub/#datahub-rest

**To Reproduce**
Create config with rest sinc and set disable_ssl_verification: true
Run ingestion and get this error:
```
datahub_api -> rest
  extra fields not permitted (type=value_error.extra)
```

**Expected behavior**
Ingestion must be executed

**Comment by anshbansal** [comment]
You should add the config file being used. This seems like a problem in the config.

**Comment by igor-kramer** [comment]
@anshbansal problem in source code. You can see that this parameter is not described in config of Rest sink

```
sink:
  type: "datahub-rest"
  config:
    disable_ssl_verification: true
    server: "https://localhost:8080"
    token: "mytoken"

```
