### ISSUE TITLE
Database profiling allow_deny_patterns : Column deny does not work.

### ISSUE THREAD

**Issue by rsontam-tc** [datahub-project/datahub#5590]
Profiling `allow_deny_patterns` do not seem to work for `deny` in PostgreSQL database, data is profiled for the excluded/denied columns and shown on the stats page.

You may follow the steps below to reproduce the issue where column level deny is not working

Goal is to ingest the table and profile only some of the columns not all, specifically the columns named `secret_value` and `secret_value2` should not be profiled.

**Table definition**
```
CREATE TABLE IF NOT EXISTS public.test_to_exclude_table_columns_from_datahub
(
    id integer NOT NULL,
    val character varying(255) COLLATE pg_catalog."default" NOT NULL,
    time_stamp timestamp without time zone NOT NULL DEFAULT clock_timestamp(),
    secret_value character varying(255) COLLATE pg_catalog."default" NOT NULL,
    secret_value2 character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT test_to_exclude_table_columns_from_datahub_pkey PRIMARY KEY (id)
)
```

**Populate Data**
```
insert into public.test_to_exclude_table_columns_from_datahub
select
	a.n
	,cast(concat(cast('val-' as varchar), to_char(a.n, '099999')) as varchar(255))
	,now()
	,(concat('secret-001:', substr(md5(random()::text), 0, 25)))::varchar(255)
	,(concat('secret-002:', substr(md5(random()::text), 0, 25)))::varchar(255)
from generate_series(20001,30000) as a(n)
```
**Specification for allow_deny**

> Specification 1

```
 profiling:
      allow_deny_patterns:
        allow: 
         - .*
        deny:
          - 'dvdrental.public.test_to_exclude_table_columns_from_datahub.secret_value*'
        ignoreCase: True
        alphabet: '[A-Za-z0-9 .-]'
```
OR

> Specification 2

```
 profiling:
      allow_deny_patterns:
        allow: 
         - .*
        deny:
          - 'dvdrental.public.test_to_exclude_table_columns_from_datahub.secret_value'
          - 'dvdrental.public.test_to_exclude_table_columns_from_datahub.secret_value2'
        ignoreCase: True
        alphabet: '[A-Za-z0-9 .-]'
```

**Expected behaviour**
Expected to see table profiled for all but the two columns `secret_value` and `secret_value2`.

**Observed behaviour**
Data Hub shows data for the two excluded/denied columns as shown in the screenshots.

_Screenshot 1 corresponds to Specification 1_
![image](https://user-images.githubusercontent.com/71721523/183517215-1f91dc75-686d-4662-b672-263d661d8924.png)

_Screenshot 2 corresponds to Specification 2_
![image](https://user-images.githubusercontent.com/71721523/183517346-9184cf13-0aa2-4886-a017-75eaf1dec825.png)

**Comment by rsontam-tc** [comment]
FYI
https://github.com/datahub-project/datahub/blob/33339e2c8933bb3b989b4052ed1b3d308624f2a0/metadata-ingestion/src/datahub/ingestion/source/ge_profiling_config.py#L80
Thanks!

**Comment by hsheth2** [comment]
Looks like this is the same issue as #5589

**Comment by rsontam-tc** [comment]
Thanks @hsheth2 , I created two bugs in case _table_ and _column_ level denies had different methods for processing.

https://github.com/datahub-project/datahub/issues/5589 is for _table_ level denies.
https://github.com/datahub-project/datahub/issues/5590 is for _column_ level denies.

Having said that I will try with the patterns you mentioned in https://github.com/datahub-project/datahub/issues/5589.

Cheers,
Raghu

**Comment by rsontam-tc** [comment]
Hello @hsheth2, 

Some progress, the following seems to be working...
```
    profile_pattern:
      allow:
        - .*
      deny:
        - 'dvdrental.public.test_to_exclude_table_from_datahub_[3-5]'
        #- 'dvdrental.public.test_to_exclude_table_columns_from_datahub.secret_value'
        - 'dvdrental.public.test_to_exclude_table_columns_from_datahub.secret_value2'    
``` 

However, specifying either or both of ignoreCase and alphabet as below causes a parse error...
```
    profile_pattern:
      allow:
        - .*
      deny:
        - 'dvdrental.public.test_to_exclude_table_from_datahub_[3-5]'
        #- 'dvdrental.public.test_to_exclude_table_columns_from_datahub.secret_value'
        - 'dvdrental.public.test_to_exclude_table_columns_from_datahub.secret_value2'     
        ignoreCase: True
        alphabet: '[A-Za-z0-9 .-]'
```

The error message is as below (regardless of either or both are used)
```
  File "/usr/local/lib/python3.7/dist-packages/yaml/parser.py", line 393, in parse_block_sequence_entry
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block collection
  in "<file>", line 32, column 9
expected <block end>, but found '?'
  in "<file>", line 36, column 9
```
It would make sense to profile data without case-sensitivity.

Looking forward to your feedback.  TIA!

**Comment by hsheth2** [comment]
@rsontam-tc that looks like an indentation error with yaml - I think the ingoreCase and alphabet lines are indented one level too deep (they should be at the same level as allow/deny). As a side note, you shouldn't need to specify alphabet manually - we ought to hide it from the config

**Comment by rsontam-tc** [comment]
OK, let me try that option, TY

**Comment by rsontam-tc** [comment]
Hi Harshal, specifying `ignoreCase` at the same level as `profile_pattern` as below...

```
    profile_pattern:
      allow:
        - .*
      deny: []
    ignoreCase: true
```
... causes the following error:

```
[2022-08-18 14:45:14,084] ERROR    {***.ingestion.run.pipeline:126} - 1 validation error for PostgresConfig
ignoreCase
  extra fields not permitted (type=value_error.extra)
[2022-08-18 14:45:14,084] INFO     {***.cli.ingest_cli:115} - Starting metadata ingestion
[2022-08-18 14:45:14,084] INFO     {***.cli.ingest_cli:133} - Finished metadata pipeline
Failed to configure source (postgres) due to 1 validation error for PostgresConfig
ignoreCase
  extra fields not permitted (type=value_error.extra)
Error: Process completed with exit code 1.
```
Cheers,
Raghu

**Comment by hsheth2** [comment]
I think the indentation is still slightly off - it should look like this:

```yml
    profile_pattern:
      allow:
        - .*
      deny: []
      ignoreCase: true
```
