### ISSUE TITLE
Athena views not retrieving definition and lineage

### ISSUE THREAD

**Issue by KulykDmytro** [datahub-project/datahub#5599]
**Describe the bug**
When extracting Athena views over standard ingest - no SQL definitions and upstream tables lineage being ingested

**To Reproduce**
1. setup `Athena` ingest file like this
```yaml
source:
  type: athena
  config:
    aws_region: eu-central-1
    s3_staging_dir: s3://athena-result-bucket/results
    work_group: primary
    include_views: true
    include_tables: false
    schema_pattern:
      deny:
        - inc
        - tmp
        - sandbox
        - sampledb
        - ^region_.*
transformers:
  - type: simple_add_dataset_tags
    config:
      tag_urns:
        - "urn:li:tag:AWS"
sink:
  type: datahub-rest
  config:
    server: http://datahub-gms:8080
```
2. ingest source
3. observe view with reduced aspects set

**Expected behavior**
Athena view should have definition (SQL) and upstream tables lineage

**Screenshots**
<img width="600" alt="image" src="https://user-images.githubusercontent.com/34435869/183725823-a06d9205-b6f4-4d8b-864f-32d7ce4ebcd1.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/34435869/183726990-a45ac43e-6c7b-44ab-be2d-846310c260f0.png">

**Additional context**
EKS - based deployment in same Account view helm chart
