### ISSUE TITLE
`pattern_add_dataset_tags` transformer's do not understand full regex and full match

### ISSUE THREAD

**Issue by KulykDmytro** [datahub-project/datahub#5699]
**Describe the bug**
using of regex start/end delimiters or full name match in transformer's rules fails to match objects
* works: `.*schema.table.*` - but it is wider than expected
* not works: `^schema.table$`
* not works: `schema.table`

**To Reproduce**
1. setup `pattern_add_dataset_tags` transformer with 
```yaml
transformers:
  - type: pattern_add_dataset_tags
    config:
      tag_pattern:
        rules:
          "^aggregate.player_segment$": [ "urn:li:tag:Player360" ]
```
2. run ingestion for `aggregate.player_segment`

**Expected behavior**
Tag `Player360` should be applied to `aggregate.player_segment` table

**Additional context**
`Glue` source is used
