### ISSUE TITLE
datahub-actions fails to connect likely due to rdkafka misconfiguration

### ISSUE THREAD

**Issue by jonmagic** [datahub-project/datahub#5706]
**Describe the bug**

I am connecting datahub to [Azure Eventhubs](https://azure.microsoft.com/en-us/services/event-hubs/) and so far have been able to get the following components working with Eventhubs:
- `datahub-gms`
- `datahub-frontend-react`
- [karapace](https://github.com/aiven/karapace) (drop in replacement for Confluent Schema Registry)

However when I try to configure `datahub-actions` I get the following error:

> `<eventhubs-namespace>.servicebus.windows.net:9093/bootstrap`: Disconnected while requesting ApiVersion: might be caused by incorrect security.protocol configuration (connecting to a SSL listener?) or broker version is < 0.10 (see api.version.request) (after 75ms in state APIVERSION_QUERY, 4 identical error(s) suppressed)

I am setting the following environment variables for `datahub-actions`:

```
KAFKA_BOOTSTRAP_SERVER=<eventhubs-namespace>.servicebus.windows.net:9093
KAFKA_PROPERTIES_SECURITY_PROTOCOL=SASL_SSL
KAFKA_PROPERTIES_SASL_MECHANISM=PLAIN
KAFKA_PROPERTIES_SASL_JAAS_CONFIG='org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://<eventhubs-namespace>.servicebus.windows.net/;SharedAccessKeyName=<shared-access-policy-name>;SharedAccessKey=<shared-access-policy-primary-key>";'
```

While these environment variables seem to work for `datahub-gms` and `datahub-frontend-react` they are either not working with `datahub-actions` OR the rdkafka configuration for `datahub-actions` is using the default of `true` for the [`api.version.request`](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md) option and may need changed to `false`.

I have been unable to figure out how to change rdkafka options for `datahub-actions` outside of the ones configured by environment variables for authentication.

**To Reproduce**
1. Setup an Eventhub in Azure Eventhubs.
2. Configure `datahub-actions` using environment variables above and the values from your Eventhub in Azure.

**Expected behavior**
Similar to the other components of datahub the datahub-actions service starts up and works.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: MacOS 12.5.1

**Additional context**
I'm using docker with docker compose to configure and start all of my datahub components. My configuration is based off of the configs from the docker folder in this project. I am able to get everything working locally and only run into problems with the single datahub-actions component when wired up to Azure Eventhubs.

**Comment by jjoyce0510** [comment]
Hiya @jonmagic !

The original issue will be in the [DataHub Actions](https://github.com/acryldata/datahub-actions) repository. It seems that we are not exposing all of the environment variables that you'd require to talk to your Kafka instance in the [default executor.yaml](https://github.com/acryldata/datahub-actions/blob/main/docker/config/executor.yaml) configuration file.

One quick way to solve this is to define your own custom `executor.yaml` file that has the correct kafka configs (simply change `source > config > connection > consumer_config`, which gives the access to a key-value map that is simply forwarded into the Python Kafka SDK. Once you've defined this file, you'd need to mount it inside the `datahub-actions` container at the following path: 

```
/etc/datahub/actions/system/conf/executor.yaml`
```

If you'd prefer an out of the box solve, we can raise an issue over on the actions repository and try to get to it soon.

Thanks
John

**Comment by jonmagic** [comment]
@jjoyce0510 thank you so much, that worked great! Fwiw we followed the code to see where the values from executor.yaml would get used and that [led us to here](https://github.com/acryldata/datahub-actions/blob/d454706c22a97525a86b3bd0c3e303167298e7ff/datahub-actions/src/datahub_actions/plugin/source/kafka/kafka_event_source.py#L107).

This is the configuration we ended up with for Azure Eventhubs:

```yaml
name: "ingestion_executor"
source:
  type: "kafka"
  config:
    connection:
      bootstrap: ${KAFKA_BOOTSTRAP_SERVER:-localhost:9092}
      consumer_config:
        security.protocol: ${KAFKA_PROPERTIES_SECURITY_PROTOCOL:-PLAINTEXT}
        sasl.mechanism: ${KAFKA_PROPERTIES_SASL_MECHANISM:-PLAIN}
        sasl.username: ${KAFKA_PROPERTIES_SASL_PLAIN_USERNAME:-datahub}
        sasl.password: ${KAFKA_PROPERTIES_SASL_PLAIN_PASSWORD:-datahub}
      schema_registry_url: ${SCHEMA_REGISTRY_URL:-http://localhost:8081}
    topic_routes:
      mcl: ${METADATA_CHANGE_LOG_VERSIONED_TOPIC_NAME:-MetadataChangeLog_Versioned_v1}
      pe: ${PLATFORM_EVENT_TOPIC_NAME:-PlatformEvent_v1}
filter:
  event_type: "MetadataChangeLogEvent_v1"
  event:
    entityType: "dataHubExecutionRequest"
    changeType: "UPSERT"
    aspectName:
      - "dataHubExecutionRequestInput"
      - "dataHubExecutionRequestSignal"
    aspect:
      value:
        executorId: "${EXECUTOR_ID:-default}"
action:
  type: "executor"
  config:
    executor_id: "${EXECUTOR_ID:-default}"
datahub:
  server: "http://${DATAHUB_GMS_HOST:-localhost}:${DATAHUB_GMS_PORT:-8080}"
  extra_headers:
    Authorization: "Basic ${DATAHUB_SYSTEM_CLIENT_ID:-__datahub_system}:${DATAHUB_SYSTEM_CLIENT_SECRET:-JohnSnowKnowsNothing}"
```
