### ISSUE TITLE
`pattern_add_dataset_tags` transformer's cannot mix regex and full match rules

### ISSUE THREAD

**Issue by KulykDmytro** [datahub-project/datahub#5726]
**Describe the bug**
In case you define regex and fullmatch rules in `pattern_add_dataset_tags` all rules will be treated as `fullmatch` which will lead to incorrect results
```yaml
...
- pattern_add_dataset_tags:
    rules:
      "schema1.table_a": [ "urn:li:tag:tag_a" ]
      ".*marketing.*": [ "urn:li:tag:marketing" ]
...
```

**Expected behavior**
Each rule should be processed independently or highlight this in documentations or make separate transformers for regex/fullmatch rules
