### ISSUE TITLE
Tableau ingestion reports invalid URN

### ISSUE THREAD

**Issue by alanmcruickshank** [datahub-project/datahub#6405]
**Describe the bug**
When loading data using `datahub.ingestion.run.pipeline` and airflow, the tableau ingestion plugin generates many urns which are apparently invalid.

Example error reported:
```
ERROR:datahub.ingestion.run.pipeline: failed to write record with workunit urn:li:chart:(tableau,a6193f44-0d83-b128-a30e-ea723b5569a4)-inputFields with ('Unable to emit metadata to DataHub GMS', {'exceptionClass': 'com.linkedin.restli.server.RestLiServiceException', 'stackTrace': 'com.linkedin.restli.server.RestLiServiceException [HTTP Status:422]: Failed to validate record with class com.linkedin.common.InputFields: ERROR :: /fields/0/schemaFieldUrn :: "Provided urn urn:li:schemaField:(urn:li:dataset:(urn:li:dataPlatform:tableau,0cab4890-b047-bb12-0a2f-958e58ccdacf,PROD),)" is invalid\n\n\tat com.linkedin.metadata.resources.entity.AspectResource.lambda$ingestProposal$3(AspectResource.java:167)', 'message': 'Failed to validate record with class com.linkedin.common.InputFields: ERROR :: /fields/0/schemaFieldUrn :: "Provided urn urn:li:schemaField:(urn:li:dataset:(urn:li:dataPlatform:tableau,0cab4890-b047-b', 'status': 422, 'id': 'urn:li:chart:(tableau,a6193f44-0d83-b128-a30e-ea723b5569a4)'}) and info {'exceptionClass': 'com.linkedin.restli.server.RestLiServiceException', 'stackTrace': 'com.linkedin.restli.server.RestLiServiceException [HTTP Status:422]: Failed to validate record with class com.linkedin.common.InputFields: ERROR :: /fields/0/schemaFieldUrn :: "Provided urn urn:li:schemaField:(urn:li:dataset:(urn:li:dataPlatform:tableau,0cab4890-b047-bb12-0a2f-958e58ccdacf,PROD),)" is invalid\n\n\tat com.linkedin.metadata.resources.entity.AspectResource.lambda$ingestProposal$3(AspectResource.java:167)', 'message': 'Failed to validate record with class com.linkedin.common.InputFields: ERROR :: /fields/0/schemaFieldUrn :: "Provided urn urn:li:schemaField:(urn:li:dataset:(urn:li:dataPlatform:tableau,0cab4890-b047-b', 'status': 422, 'id': 'urn:li:chart:(tableau,a6193f44-0d83-b128-a30e-ea723b5569a4)'}
```

or a similar example which appears later in the logs but is formatted nicer:

```
{
    'error': 'Unable to emit metadata to DataHub GMS',
    'info': {'exceptionClass': 'com.linkedin.restli.server.RestLiServiceException',
                         'stackTrace': 'com.linkedin.restli.server.RestLiServiceException [HTTP Status:422]: Failed to validate record with class '
                                       'com.linkedin.common.InputFields: ERROR :: /fields/0/schemaFieldUrn :: "Provided urn '
                                       'urn:li:schemaField:(urn:li:dataset:(urn:li:dataPlatform:tableau,0cab4890-b047-bb12-0a2f-958e58ccdacf,PROD),)" '
                                       'is invalid\n'
                                       '\n'
                                       '\tat com.linkedin.metadata.resources.entity.AspectResource.lambda$ingestProposal$3(AspectResource.java:167)',
                         'message': 'Failed to validate record with class com.linkedin.common.InputFields: ERROR :: /fields/0/schemaFieldUrn :: '
                                    '"Provided urn urn:li:schemaField:(urn:li:dataset:(urn:li:dataPlatform:tableau,0cab4890-b047-b',
                         'status': 422,
                         'id': 'urn:li:chart:(tableau,a6193f44-0d83-b128-a30e-ea723b5569a4)'}}

```

**To Reproduce**
We're building the pipeline using `Pipeline.create(yaml_content)` and the yaml config for the pipeline is:
```yaml
pipeline_name: "tableau_airflow_ingest"

source:
  type: tableau
  config:
    connect_uri: '{TABLEAU_URL}'
    site: ""
    projects: null
    token_name: '{TABLEAU_TOKEN_NAME}'
    token_value: '{TABLEAU_TOKEN_VALUE}'
    ingest_tags: true
    ingest_owner: true
    ingest_tables_external: true
    extract_column_level_lineage: True

    stateful_ingestion:
      enabled: True # False by default
      remove_stale_metadata: True # default value

transformers:
  - type: "pattern_add_dataset_tags"
    config:
      tag_pattern:
        rules:
          # Any untitled datasources should have names
          ".*Custom SQL Query.*": ["urn:li:tag:NeedsDescriptiveName"]

sink:
  type: datahub-rest
  config:
    server: '{DATAHUB_REST_ENDPOINT}'
```

(secrets are ingested before parsing as yaml)

The pipeline _does_ run, but produces many many of the kinds of errors mentioned above. Not all referring to the same entity, but there appears to be something the way the urns are generated which the GMS endpoint really doesn't like.

**Expected behavior**
No errors :)

**Additional context**
We're running `acryl-datahub[dbt,tableau,snowflake]==0.9.0.5` in the airflow environment for ingestion and `0.2.110` of the helm release for the main datahub deployment.
