### ISSUE TITLE
Ingest Clickhouse show None database

### ISSUE THREAD

**Issue by bigdata-spec** [datahub-project/datahub#6544]
Hello，May I ask you some questions?
I want to know this picture：

![image](https://user-images.githubusercontent.com/23710717/203729094-d554100d-4f67-49b3-8c4d-bd88d88cd6a6.png)

my version ：0.9.2
why show None？How to modify this show？

I run `datahub ingest -c ck_to_datahub_rest.yml`

```
source:
  type: clickhouse
  config:
    # Coordinates
    host_port: xxxx:8123

    # Credentials
    username: ckdev
    password: Bigdata123456

    # Options
    platform_instance: Clickhouse-dev
    database_alias: ck
    env: DEV

    include_views: True # whether to include views, defaults to True
    include_tables: True # whether to include views, defaults to True

transformers:
    -
        type: simple_add_dataset_tags
        config:
            tag_urns:
                - 'urn:li:tag:ck-dev'
sink:
    type: datahub-rest
    config:
        server: 'http://localhost:8086'
```

**Comment by laulpogan** [comment]
Hi @jiangbiao910  this seems like a troubleshooting issue, rather than a bug. We're happy to provide community support on our Slack channel, but currently reserve git issues for bugs.

If you're still having trouble, please join us at [[slack.datahubproject.io](https://slack.datahubproject.io/)](https://slack.datahubproject.io/) and we can troubleshoot there. For now, I'm going to close this issue.

**Comment by bobelev** [comment]
It's a bug actually. Clickhouse ingestion treats database parameter in config as an actual database entity but in fact gathers every `(database, table)` from `system.tables`. 

Lets say we have 2 databases in clickhouse server: `analytics` and `users`.

If database is omitted in config we'll get `None` as parent container for all. So we'll get tables:

```
clickhouse > None > analytics > table1
clickhouse > None > users > table2
```

To reproduce this behavior remove `database: clickhousedb` from https://github.com/datahub-project/datahub/blob/master/metadata-ingestion/tests/integration/clickhouse/clickhouse_to_file.yml

If we set database in config, let's say analytics, we'll get the following:

```
clickhouse > analytics > analytics > table1
clickhouse > analytics > users > table2
```

Even test results in `clickhouse_mces_golden.json` show this behaviour.


Expected results are: 
```
clickhouse > analytics > table1
clickhouse > users > table2
```

Expected behavior:
- always use `database` from `system.tables` as a parent container for tables
- don't ingest information from different databases if `database` is specified in config

**Comment by bobelev** [comment]
@laulpogan, reopen this issue please

**Comment by bobelev** [comment]
@laulpogan, reopen this issue please

**Comment by alplatonov** [comment]
This bug affect me too.

**Comment by alplatonov** [comment]
How to reproduce on the dev server:
1. Download clickhouse in docker. [Link](https://hub.docker.com/r/clickhouse/clickhouse-server/)

```
docker pull clickhouse/clickhouse-server:22.4.4
docker run -d -p 9000:9000 -p 8123:8123 -p 9009:9009 --name some-clickhouse-server --ulimit nofile=262144:262144 clickhouse/clickhouse-server:22.4.4
docker run -d -e CLICKHOUSE_DB=my_database -e CLICKHOUSE_USER=username -e CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1 -e CLICKHOUSE_PASSWORD=password -p 9000:9000/tcp clickhouse/clickhouse-server:22.4.4
```
2. Download the clickhouse client [link](https://altinity.com/blog/altinity-introduces-macos-homebrew-tap-for-clickhouse)
`brew install altinity/clickhouse/clickhouse`
3. Create database and ingest some data:
db db1 – table dish
db db2 – table menu
```
clickhouse-client --user default --password 'dadada'
create database db1;
create database db2;

```
Use [link](https://clickhouse.com/docs/en/getting-started/example-datasets/menus) for dataset and table creation.
4. Ingest data with config

```
source:
  type: clickhouse
  config:
    sqlalchemy_uri: 'clickhouse+native://default:dadada@localhost/?compression=lz4&secure=false'
    platform_instance: docker_on_localhost
sink:
  type: "datahub-rest"
  config:
    server: "http://localhost:8080"
```
5. Look at the metadata; at UI you can see:
```
Table -> ClickHouse -> docker_on_localhost -> [urn:li:container:e3fd473d86c798335f51661152053c17] ->  db1 -> dish
Table ->  ClickHouse -> docker_on_localhost -> [urn:li:container:e3fd473d86c798335f51661152053c17]  -> db2 -> menu
schema -> ... -> db1
Database -> ClickHouse ->docker_on_localhost -> urn:li:container:e3fd473d86c798335f51661152053c17
```
6. Modify sqlalchemy URL to 
`
sqlalchemy_uri: 'clickhouse+native://default:dadada@localhost/db1?compression=lz4&secure=false'
`
and download metadata again.
Now you can see in UI:
`Table ->  ClickHouse -> docker_on_localhost -> db1 -> db2 -> menu`
