### ISSUE TITLE
Wrong semantics in Okta connector output

### ISSUE THREAD

**Issue by JakubBialoskorski** [datahub-project/datahub#6595]
**Describe the bug**
[Okta connector](https://datahubproject.io/docs/generated/ingestion/sources/okta/) shows wrong output after successful ingestion:

`Client-Server Incompatible❗ Your client version 0.8.45 is newer than your server version 0.9.1. Downgrading the cli to 0.9.1 is recommended.`

**To Reproduce**
1. Add new Okta ingestion via UI
2. Run the following recipe:
```
source:
    type: okta
    config:
        okta_api_token: '${OKTA_DEV_API_TOKEN}'
        ingest_users: true
        okta_domain: YOURDOMAIN.okta.com
        ingest_groups: false
        ingest_group_membership: false
        page_size: 100
        delay_seconds: 0.1
        include_deprovisioned_users: false
        include_suspended_users: false
```
3. After the successful ingestion, check logs. At the very end you'll see this mismatch error.

**Expected behavior**
It should state that 0.9.1 is **newer** than 0.8.45, not the other way around.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 107.0.5304.121

**Additional context**
- DataHub version: v0.9.1 (deployed via Helm to EKS)
- acryl-datahub-actions version: v0.0.8
- chart version: datahub-0.2.111
- CLI version: 0.9.1
