### ISSUE TITLE
LookML ingestion config with github_info failes 

### ISSUE THREAD

**Issue by szalai1** [datahub-project/datahub#6766]
# Reproduce 

```
# conf.yaml
source:
  type: lookml
  config:
    github_info:
      deploy_key: dfasd
      repo: 'a/b'
    api:
        base_url: 'https://XXXXX.eu.looker.com'
        client_secret: 'xxx'
        client_id: XXXXXXXXXXX
    project_name: my_project
```

`datahub ingest -c conf.yaml`

Error: 
```
base_folder
  base_folder is not provided. Neither has a github deploy_key or deploy_key_file been provided (type=value_error)
```

Related code: https://github.com/datahub-project/datahub/blob/master/metadata-ingestion/src/datahub/ingestion/source/looker/lookml_source.py#L283
