### ISSUE TITLE
Source column description from DBT is missing in Datahub

### ISSUE THREAD

**Issue by maver1ck** [datahub-project/datahub#6887]
**Describe the bug**
Source column description from DBT is not populated to Datahub 

**To Reproduce**
1. Create sample DBT model (I used this one: https://github.com/dbt-labs/trino-dbt-tpch-demo)
2. Set up description field in sources.yml
3. Run dbt
4. Ingest dbt json files into datahub

**Expected behavior**
I want to see column descriptions from DBT in Datahub

**Screenshots**
Datahub
![image](https://user-images.githubusercontent.com/4006010/209960010-271e53d4-91e1-471c-8950-f4ac46b37df7.png)
DBT Docs
![image](https://user-images.githubusercontent.com/4006010/209960186-727ba239-ec45-4800-b8f6-759d97d881ad.png)

**Comment by jjoyce0510** [comment]
Hi @maver1ck ! We are investigating this at present. If you click on the "dbt" source in the right side panel, do you see the descriptions (based on what you've posted I'm assuming not)

Cheers
John

**Comment by jjoyce0510** [comment]
We should be extracting the "comments" from DBT sources. I can confirm we are seeing for sources.

Can you please confirm that when navigating to the DBT dedicated source page (right side) you cannot see it? If yes, then I think we've found a real bug in the rendering layer.

Cheers
John

**Comment by maver1ck** [comment]
I'm sending screenshot from dbt source. There is no columns at all.
Sources are from this file:
https://github.com/dbt-labs/trino-dbt-tpch-demo/blob/main/models/staging/tpch/tpch_sources.yml

This is ingestion config
```
source:
  type: "dbt"
  config:
    # Coordinates
    # To use this as-is, set the environment variable DBT_PROJECT_ROOT to the root folder of your dbt project
    manifest_path: "/Users/maverick/src/ezdihar/trino-dbt-tpch-demo/target/manifest.json"
    catalog_path: "/Users/maverick/src/ezdihar/trino-dbt-tpch-demo/target/catalog.json"
    sources_path: "/Users/maverick/src/ezdihar/trino-dbt-tpch-demo/target/sources.json" # optional for freshness
    test_results_path: "/Users/maverick/src/ezdihar/trino-dbt-tpch-demo/target/run_results.json" # optional for recording dbt test results after running dbt test
    platform: "trino"
    target_platform: "trino" # e.g. bigquery/postgres/etc.
    query_tag_mapping:
      tag:
          match: ".*"
          operation": "add_tag"
          config:
            tag: "{{ $match }}"
    

# sink configs

sink:
  type: "datahub-rest"
  config:
    # IP of the pod on k8s
    server: "http://127.0.0.1:8080"
```

![image](https://user-images.githubusercontent.com/4006010/211026727-1c5dd962-fd5a-43ab-9f7b-1213a7bf43c0.png)
