### ISSUE TITLE
dot character issue in table name s3://my-bucket/foo/tests/{table}/*.*

### ISSUE THREAD

**Issue by YuriyGavrilov** [datahub-project/datahub#7033]
**Describe the bug**
There is an issue with folders with dot character. root (test) folder will be avoided if we try to ingest 3 folders like test, test.esho, test.esho2.  

**To Reproduce**
1. Go to 'ingestion and create s3 ingestion with folder like "   include: 's3://edp-edl-uat/data/datahub_test/{table}/star.star'"'
2. Click on 's3 and create 3 directories with any same parquet files. like test, test.esho, test.esho2' and try to ingest.
3. Scroll down to the results 
4. See error that there is no first folder like "test" (without dot)

**Expected behavior**
include test folder 

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

![image](https://user-images.githubusercontent.com/44679014/212322118-9a462010-735a-4229-95b8-3d41f459d7f2.png)
but there is one more folder 
![image](https://user-images.githubusercontent.com/44679014/212322235-4980fa5e-1212-43bd-a386-1f3947c7d79b.png)

there is no such issue with "_" character 
... works good.

![image](https://user-images.githubusercontent.com/44679014/212322943-9270609f-57f0-4534-a476-ae64b32014be.png)

![image](https://user-images.githubusercontent.com/44679014/212323005-5ff577af-22da-4ce7-acd0-b5bebdd17670.png)

two logs attached. 

[logs_with_dot.log](https://github.com/datahub-project/datahub/files/10411678/logs_with_dot.log)
[logs_with__.log](https://github.com/datahub-project/datahub/files/10411679/logs_with__.log)

**Comment by mmmeeedddsss** [comment]
@YuriyGavrilov Have you tried using `s3://edp-edl-uat/data/datahub_test/{table}/star` (without .star) so that all files are ingested even if they don't contain a dot character in the names? It might be worth a shot.

Also, there is a filter logic as follows for s3 files: https://github.com/datahub-project/datahub/blob/e41b455e14e376985bc577a2b6247449800937e0/metadata-ingestion/src/datahub/ingestion/source/aws/path_spec.py#L74

It seems like you need to specify a `default_extension` together with `include`, to cover files that have no extension in their names. 

(I'm not using s3 ingestion and haven't tested what I wrote so I'm sorry if these do not make sense :D )

**Comment by YuriyGavrilov** [comment]
@mmmeeedddsss didn't work 
[exec-urn_li_dataHubExecutionRequest_03c252ef-6d9a-4d1f-b2b3-b89d1b75ad90.log](https://github.com/datahub-project/datahub/files/10423859/exec-urn_li_dataHubExecutionRequest_03c252ef-6d9a-4d1f-b2b3-b89d1b75ad90.log)

**Comment by mmmeeedddsss** [comment]
@YuriyGavrilov In the logs you shared, the exception says that the extension you specified does not included in the known file types. Could you share how do you configure path_specs?

```
'[2023-01-16 08:32:27,803] ERROR    {datahub.entrypoints:189} - Failed to configure the source (s3): 1 validation error for '
'DataLakeSourceConfig\n'
'path_specs -> 0 -> __root__\n'
"  file type specified () in path_spec.include is not in specified file types. Please select one from ['csv', 'tsv', 'json', 'parquet', "
'\'avro\'] or specify ".*" to allow all types (type=value_error)\n',
```

**Comment by YuriyGavrilov** [comment]
@mmmeeedddsss something like this s3://my-bucket/foo/tests/{table}/    ( with out star) also tryed *.parquet

**Comment by mmmeeedddsss** [comment]
@YuriyGavrilov Could you try something like the following:

```
...:
    path_specs:
        - include: "s3://my-bucket/foo/tests/{table}/*"
           default_extension: "parquet"
         - include: "s3://my-bucket/foo/tests/{table}/*.*"
           default_extension: "parquet"
```
or
```
...:
    path_specs:
        - include: "s3://my-bucket/foo/tests/{table}/*"
           default_extension: "parquet"
```


It might be best if you can read the code in here: https://github.com/datahub-project/datahub/blob/e41b455e14e376985bc577a2b6247449800937e0/metadata-ingestion/src/datahub/ingestion/source/aws/path_spec.py#L58

And tune your parameters accordingly if the above not works. I am not 100% sure what you desire.(e.g * and ** means different things, which one fits to you? )

**Comment by YuriyGavrilov** [comment]
...:
    path_specs:
        - include: "s3://my-bucket/foo/tests/{table}/*"
           default_extension: "parquet"


does not work.

...:
    path_specs:
        - include: "s3://my-bucket/foo/tests/{table}/*"
           default_extension: "parquet"
         - include: "s3://my-bucket/foo/tests/{table}/*.*"
           default_extension: "parquet"


does not work too 

@mmmeeedddsss  two solution avoid folder like "test" without dot.

**Comment by mmmeeedddsss** [comment]
Unfortunately, I cannot suggest anything further. I'm surprised that the first one:
```
    path_specs:
        - include: "s3://my-bucket/foo/tests/{table}/*"
           default_extension: "parquet"
         - include: "s3://my-bucket/foo/tests/{table}/*.*"
           default_extension: "parquet"
```
does not work. Maybe you can ask further on datahub slack channel or wait somebody from the core team to answer. Sorry
