### ISSUE TITLE
Datahub-action image has permission error while docker-composing datathub

### ISSUE THREAD

**Issue by DeepFlame-JR** [datahub-project/datahub#7571]
When I run this code. 
`sudo docker-compose -f docker-compose-without-neo4j-m1.quickstart.yml up -d`

I got this error. (`docker logs quickstart-datahub-actions-1`)
```
2023/03/14 03:20:31 Waiting for: http://datahub-gms:8080/health
2023/03/14 03:20:31 Received 200 from http://datahub-gms:8080/health
ls: cannot access '/etc/datahub/actions/system/conf/': Operation not permitted
No system action configurations found. Not starting system actions.
ls: cannot access '/etc/datahub/actions/conf/': Operation not permitted
No user action configurations found. Not starting user actions.
Usage: datahub-actions actions [OPTIONS] COMMAND [ARGS]...

  Execute one or more Actions Pipelines

Options:
  --help  Show this message and exit.

Commands:
  run*     Execute one or more Actions Pipelines
  version  Print version number and exit.
2023/03/14 03:20:31 Command finished successfully.
```

This is a part of docker compose file.
```
  datahub-actions:
    depends_on:
    - datahub-gms
    environment:
    - DATAHUB_GMS_HOST=datahub-gms
    - DATAHUB_GMS_PORT=8080
    - DATAHUB_GMS_PROTOCOL=http
    - DATAHUB_SYSTEM_CLIENT_ID=__datahub_system
    - DATAHUB_SYSTEM_CLIENT_SECRET=JohnSnowKnowsNothing
    - KAFKA_BOOTSTRAP_SERVER=broker:29092
    - KAFKA_PROPERTIES_SECURITY_PROTOCOL=PLAINTEXT
    - METADATA_AUDIT_EVENT_NAME=MetadataAuditEvent_v4
    - METADATA_CHANGE_LOG_VERSIONED_TOPIC_NAME=MetadataChangeLog_Versioned_v1
    - SCHEMA_REGISTRY_URL=http://schema-registry:8081
    hostname: actions
    user: 0:0
    image: acryldata/datahub-actions:${ACTIONS_VERSION:-head}
    restart: on-failure:5
```

Please tell me how to fix it.
Thanks in advance.

**Desktop (please complete the following information):**
 - OS: Red Hat 7.4

**Additional context**
I ran this code in company's network. so I can't use the internet like `datahub docker quickstart`

**Comment by DeepFlame-JR** [comment]
I solved this error myself.
I just added `privileged: true` option.

I will leave it up to someone to help. 🤗
```
datahub-actions:
  depends_on:
  - datahub-gms
  environment:
  - DATAHUB_GMS_HOST=datahub-gms
  - DATAHUB_GMS_PORT=8080
  - DATAHUB_GMS_PROTOCOL=http
  - DATAHUB_SYSTEM_CLIENT_ID=__datahub_system
  - DATAHUB_SYSTEM_CLIENT_SECRET=JohnSnowKnowsNothing
  - KAFKA_BOOTSTRAP_SERVER=broker:29092
  - KAFKA_PROPERTIES_SECURITY_PROTOCOL=PLAINTEXT
  - METADATA_AUDIT_EVENT_NAME=MetadataAuditEvent_v4
  - METADATA_CHANGE_LOG_VERSIONED_TOPIC_NAME=MetadataChangeLog_Versioned_v1
  - SCHEMA_REGISTRY_URL=http://schema-registry:8081
  hostname: actions
  user: 0:0
  privileged: true
  image: acryldata/datahub-actions:${ACTIONS_VERSION:-head}
  restart: on-failure:5
 ```
