### ISSUE TITLE
Schema Pattern Option in Athena Recipe not ingesting any metadata

### ISSUE THREAD

**Issue by vravi-li** [datahub-project/datahub#7643]
**Describe the bug**
Using the schema pattern option in Athena recipe does not ingest any metadata from the underlying tables. I am trying to ingest multiple databases from Athena. The only way to do this right now is to put multiple database names in database option in the recipe, and I have more than 100 tables. There is no option of database pattern in the ingestion recipe unfortunately.

**To Reproduce**
Try ingesting data with the attached recipes.

Recipe #1
```
source:
    type: athena
    config:
        aws_region: us-east-1
        work_group: primary
        database: auto_aggregation
        query_result_location: 's3://......'
```

Recipe #2
```
source:
    type: athena
    config:
        aws_region: us-east-1
        work_group: primary
        schema_pattern:
            allow:
                - '^auto_*'
        query_result_location: 's3://......'
```

**Expected behavior**
The metadata is ingested properly.

Screenshots
![image](https://user-images.githubusercontent.com/101206509/226418658-f52215e2-6319-425a-8383-dd9ef75c16bc.png)

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser: Chrome

**Additional context**
