### ISSUE TITLE
datahub-acryl-datahub-actions MSK with SASL_SSL

### ISSUE THREAD

**Issue by tieungao88** [datahub-project/datahub#7807]
**Describe the bug**
I deploy datahub with k8s. And I have problem in log:
`%6|1681355763.464|FAIL|rdkafka#consumer-1| [thrd:b-2.devdwhdatahubmsk.xxx.c5.kafka.ap-southeast-1.amazonaws.c]: b-2.devdwhdatahubmsk.xxx.c5.kafka.ap-southeast-1.amazonaws.com:9096/bootstrap: Disconnected while requesting ApiVersion: might be caused by incorrect security.protocol configuration (connecting to a SSL listener?) or broker version is < 0.10 (see api.version.request) (after 1ms in state APIVERSION_QUERY, 4 identical error(s) suppressed)`

This my config:
```
global:
  ## Add below to enable SSL for kafka
    credentialsAndCertsSecrets:
      name: sasl-jass-config
      secureEnv:
        sasl.jaas.config: sasl_jaas_config
    #  name: datahub-certs
    #  path: /mnt/datahub/certs
    #  secureEnv:
    #    ssl.key.password: datahub.linkedin.com.KeyPass
    #    ssl.keystore.password: datahub.linkedin.com.KeyStorePass
    #    ssl.truststore.password: datahub.linkedin.com.TrustStorePass
    #    kafkastore.ssl.truststore.password: datahub.linkedin.com.TrustStorePass
  #
    springKafkaConfigurationOverrides:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-512

```
sasl_jaas_config:
`org.apache.kafka.common.security.scram.ScramLoginModule required username=xxxxx password=xxxx;`

Please help me!

Thanks.
