### ISSUE TITLE
Profiling of numerical OracleDB fields

### ISSUE THREAD

**Issue by GreatLanser** [datahub-project/datahub#7879]
**Describe the bug**

Error in profiling numeric type fields. In the place where the Data Hub performs type checks ([here](https://github.com/datahub-project/datahub/blob/master/metadata-ingestion/src/datahub/ingestion/source/ge_data_profiler.py#L611)) it expects only the following types: `int`, `number` and `float`. However, only `numeric` and `float` types exist in Oracle DB. Thus, if the field type is `numeric`, profiling does not occur.

**To Reproduce**
1.  Create table in OracleDB:
```
CREATE TABLE HR.test (
	int_col int,
	num_col numeric(19, 12),
	float_col float
);
```
2. Check Column native oracle types.

2. Profile the table using the recipe:
```
pipeline_name: "Oracle_HR"
source:
    type: oracle
    config:
        host_port: "localhost:1521"
        username: HR
        password: HR
        service_name: XEPDB1
        schema_pattern:
            allow:
                - HR
        profiling:
            enabled: true
            query_combiner_enabled: false
        stateful_ingestion:
            enabled: true
        profile_pattern:
            allow:
            - "HR.*.*"
sink:
    type: "datahub-rest"
    config:
        server: "http://localhost:8080"
```
Start ingestion from the CLI:
`datahub ingest -c Oracle_HR.dhub.yaml`
3. Check the profiling in the UI
4. Numerous warnings in the output during ingenction execution such as:
`[2023-04-21 11:36:20,313] WARNING  {great_expectations.dataset.sqlalchemy_dataset:2131} - No recognized sqlalchemy types in type_list for current dialect.`

**Expected behavior**
Profiling of all columns has been completed (min, max, etc.)

**Screenshots**
Column native oracle types:
![image](https://user-images.githubusercontent.com/89299358/233627441-05913c50-4efd-4d32-9190-2ef98e0c6b99.png)

The result of profiling in the UI:
![image](https://user-images.githubusercontent.com/89299358/233628090-d9c8b304-4078-4795-9786-e191c733e7d5.png)

**Desktop:**
 - OS: Linux Ubuntu 22.04 (WSL)
 - Database: Oracle Database 21c Express Edition Release 21.0.0.0.0
 - Datahub version (quickstart): 0.10.1.1
 - Python: 3.10.6

**Additional context**
[The thread in the slack, in which they came to the conclusion that this is a bug](https://datahubspace.slack.com/archives/C029A3M079U/p1681902908094999)
