### ISSUE TITLE
BigQuery View Labels Not Imported as Datahub Tags During Ingestions

### ISSUE THREAD

**Issue by smisachsen** [datahub-project/datahub#8114]
**Describe the bug**
The bug prevents BigQuery View labels from being imported as Datahub tags when transferring data from BigQuery. Despite enabling the `capture_table_label_as_tag: true` setting, it only captures labels for BigQuery Tables, while BigQuery View labels are not being imported as Datahub tags

**To Reproduce**
1. Ingest data from BigQuery with config:
```
source:
    type: bigquery
    config:
        project_id_pattern:
            allow:
                - GCP_PROJECT_WITH_VIEWS_WITH_LABELS
        include_views: true
        capture_table_label_as_tag: true
```

**Expected behavior**
Bigquery View Labels are imported as Datahub tags
