### ISSUE TITLE
Integration with dbt tests does not show details of failed test

### ISSUE THREAD

**Issue by zhyzhkea** [datahub-project/datahub#8256]
**Describe the bug**
Integration with dbt tests does not show details of failed tests. Tests were invoked via dbt-rpc server. 

**To Reproduce**
1. Follow this instructions: https://datahubproject.io/docs/generated/ingestion/sources/dbt
2. Recipe file:
```
source:
  type: "dbt"
  config:
    # Coordinates
    # To use this as-is, set the environment variable DBT_PROJECT_ROOT to the root folder of your dbt project
    manifest_path: "${DBT_PROJECT_ROOT}/target/manifest.json"
    catalog_path: "${DBT_PROJECT_ROOT}/target/catalog.json"
    #sources_path: "${DBT_PROJECT_ROOT}/target/sources_file.json" # optional for freshness
    test_results_path: "${DBT_PROJECT_ROOT}/target/run_results.json" # optional for recording dbt test results after running dbt test
    # Options
    target_platform: "snowflake" # e.g. bigquery/postgres/etc.
```

3. datahub ingest -c ./dbt-recipe.yml

**Expected behavior**
Should be able to see details of the failed tests and  proper count numbers

**Screenshots**

![image](https://github.com/datahub-project/datahub/assets/34140723/0b473ecf-9ee0-4187-8984-92d8cac3aac5)

**Desktop (please complete the following information):**
 - OS: WSL2/Ubuntu 22.04
 - Browser: Chrome
 - Version: Latest

```
 cd /mnt/c/work/datahub
 conda create -n datahub python=3.8
 conda activate datahub
 python3 -m pip install --upgrade pip wheel setuptools
 python3 -m pip install --upgrade acryl-datahub
 datahub version
 datahub docker quickstart 
```

**Additional context**
