### ISSUE TITLE
no matching manifest for linux/arm/v8 in the manifest list entries

### ISSUE THREAD

**Issue by GrMoney93** [datahub-project/datahub#8553]
I am certain that this is a fault on my end, but when running the command:

docker compose up -d

I get the error saying that there is "no matching manifest for linux/arm/v8 in the manifest list entries"

I can see from the URL that docker compose points to (https://github.com/immich-app/immich/pkgs/container/immich-server) that there is a v7 version supported.

Is the v7 version compatible with my Raspberry Pi version and how can I tell docker compose to use that version if it is?

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

**Comment by GrMoney93** [comment]
Okay so I got a little bit further by adding:

platform: linux/arm/v7

to all of the services that were directly to do with immich but not typesense, database or redis.

e.g.

```
services:
  immich-server:
    platform: linux/arm/v7
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always
```

This resulted in more stuff being pulled? but I still got the same error message and the output says:

typesense Error

I tried removing the @sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd from the image but that also did not resolve the issue I am having.

Thank you
