### ISSUE TITLE
Platform Instance is missing on datasets for S3 ingestion

### ISSUE THREAD

**Issue by terratrue-daniel** [datahub-project/datahub#8584]
**Describe the bug**
Despite specifying a `platform_instance` in the S3 recipe, it is missing when we query for it.

Recipe:
```
source:
    type: s3
    config:
        path_specs:
            -
                include: 's3://tt-daniel-test/*.*'
        aws_config:
            aws_access_key_id: '${S3_AWS_ACCESS_KEY_ID}'
            aws_secret_access_key: '${S3_AWS_SECRET_ACCESS_KEY}'
            aws_region: us-east-2
        env: PROD
        platform_instance: daniel-s3-manual
        stateful_ingestion:
            enabled: true
            remove_stale_metadata: true
sink:
    type: datahub-rest
    config:
        server: 'http://datahub-datahub-gms:8080/'
        max_threads: 1
        mode: SYNC
```

Query result on dataset:
```
{
  "data": {
    "dataset": {
      "urn": "urn:li:dataset:(urn:li:dataPlatform:s3,daniel-s3-manual.tt-daniel-test/food_parquet.parquet,PROD)",
      "type": "DATASET",
      "lastIngested": 1690920409755,
      "dataPlatformInstance": null
    }
  },
  "extensions": {}
}
```

Platform instance is missing from aspect:
```
+---------------------------------------------------------------------------------------------------+----------------------+---------+---------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------+----------------------------------+------------+
| urn                                                                                               | aspect               | version | metadata                              | systemmetadata                                                                                                                                 | createdon                  | createdby                        | createdfor |
+---------------------------------------------------------------------------------------------------+----------------------+---------+---------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------+----------------------------------+------------+
| urn:li:dataset:(urn:li:dataPlatform:s3,daniel-s3-manual.tt-daniel-test/food_parquet.parquet,PROD) | dataPlatformInstance |       0 | {"platform":"urn:li:dataPlatform:s3"} | {"registryVersion":"0.0.0.0-dev","runId":"ca3f8f3d-5201-46a9-ab04-f271252c9f8e","registryName":"unknownRegistry","lastObserved":1690919105402} | 2023-08-01 19:45:05.409000 | urn:li:corpuser:__datahub_system | NULL       |
+---------------------------------------------------------------------------------------------------+----------------------+---------+---------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------+----------------------------------+------------+
```

**To Reproduce**
1. Create a recipe for S3 ingestion with `platform_instance` set.
2. Run the ingestion
3. Copy the URN from any of the datasets ingested
4. Run the query:
```
query getDataset {
  dataset(urn: <URN>) {
    urn
    type
    lastIngested
    dataPlatformInstance {
      urn
    }
  }
}
```
5. `dataPlatformInstance` is `null`.

**Expected behavior**
If a platform instance is specified, the platform instance should be present on the dataset when I query for it.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: iOS Ventura
 - Browser: Chrome
 - Version: 115.0.5790.114

**Additional context**
CLI Version 0.10.5.4
