### ISSUE TITLE
[BUG] How to  Ingest iceberg metadata with alluxio in datahub

### ISSUE THREAD

**Issue by SamealD** [datahub-project/datahub#8634]
i create a iceberg_to_datahub_rest.yml as flow:
```
source:
  type: iceberg
  config:
    localfs: "alluxio://ip:19998/oss/landing"
    max_path_depth: 2
    platform_instance: "landing"
    user_ownership_property: "alluxio"
    table_pattern:
      ignoreCase: true
    profiling:
      enabled: true
sink:
  type: datahub-rest
  config:
    server: 'http://ip:8080'
```

we use alluxio store iceberg metadata, but it get error:
![image](https://github.com/datahub-project/datahub/assets/40708512/4775201f-f520-4ca1-b7bc-fb97c1ac5cfa)

Is there something wrong with what I wrote?
Is there something wrong with what I wrote or is datahub not supported？
what should i do?
