### ISSUE TITLE
BigQuery nested fields missing descriptions

### ISSUE THREAD

**Issue by maaaikoool** [datahub-project/datahub#8763]
**Describe the bug**
BigQuery schemaMetadata aspect is missing description in record fields that are not the root record field.

**To Reproduce**
1. Ingest any dataset with a record.
```
pipeline_name: bigquery_test
source:
  type: bigquery
  config:
    match_fully_qualified_names: true
    include_table_lineage: false
    include_usage_statistics: false
    include_views: false
    project_id: pepe
    schema_pattern:
      allow:
      - "pepe.dataset"
    table_pattern:
      allow:
        - .*some_table_with_record
    use_date_sharded_audit_log_tables: false
    use_exported_bigquery_audit_metadata: false
    profiling:
      enabled: false
sink:
  type: file
  config:
      filename: out.json
```

**Expected behavior**
All fields should have description

**Screenshots**

<img width="1429" alt="bigquery" src="https://github.com/datahub-project/datahub/assets/3258096/bb50a59b-9f73-4802-84b4-c9b8c9ad8346">
<img width="1269" alt="datahub" src="https://github.com/datahub-project/datahub/assets/3258096/7e5ba80c-bc77-4744-9839-6187df9ef299">

**Additional context**
Tested with latest version master e7d140f82df393b98821f8a49e74ae3995a01ead
