### ISSUE TITLE
Druid profiling fails because of missing CREATE keyword in SQL API

### ISSUE THREAD

**Issue by ubiquitousbyte** [datahub-project/datahub#9249]
**Describe the bug**
Generating profiling metadata out of Druid does not work, because the source tries to create a temporary table but cannot because Druid does not understand the `CREATE` keyword, so a statement like 
```sql
CREATE TEMPORARY TABLE "ge_temp_5e5046ea" AS SELECT * 
FROM "sys"."server_segments"
```

fails on the Druid broker with
```
[2023-11-16 13:31:23,152] Exception while processing sqlQueryId[6a0d4ef2-ae1c-41df-9976-31345fe07904] (org.apache.druid.error.DruidException: Received an unexpected token [CREATE] (line [1], column [1]), acceptable options: ["INSERT", "UPSERT", "EXPLAIN", "SET", "RESET", "ALTER", "WITH", "+", "-", "NOT", "EXISTS", <UNSIGNED_INTEGER_LITERAL>, <DECIMAL_NUMERIC_LITERAL>, <APPROX_NUMERIC_LITERAL>, <BINARY_STRING_LITERAL>, <PREFIXED_STRING_LITERAL>, <QUOTED_STRING>, <UNICODE_STRING_LITERAL>, "TRUE", "FALSE", "UNKNOWN", "NULL", <LBRACE_D>, <LBRACE_T>, <LBRACE_TS>, "DATE", "TIME", "TIMESTAMP", "INTERVAL", "?", "CAST", "EXTRACT", "POSITION", "CONVERT", "TRANSLATE", "OVERLAY", "FLOOR", "CEIL", "CEILING", "SUBSTRING", "TRIM", "CLASSIFIER", "MATCH_NUMBER", "RUNNING", "PREV", "NEXT", "JSON_EXISTS", "JSON_VALUE", "JSON_QUERY", "JSON_OBJECT", "JSON_OBJECTAGG", "JSON_ARRAY", "JSON_ARRAYAGG", <LBRACE_FN>, "MULTISET", "ARRAY", "PERIOD", "SPECIFIC", <IDENTIFIER>, <QUOTED_IDENTIFIER>, <BACK_QUOTED_IDENTIFIER>, <BRACKET_QUOTED_IDENTIFIER>, <UNICODE_QUOTED_IDENTIFIER>, "ABS", "AVG", "CARDINALITY", "CHAR_LENGTH", "CHARACTER_LENGTH", "COALESCE", "COLLECT", "COVAR_POP", "COVAR_SAMP", "CUME_DIST", "COUNT", "CURRENT_DATE", "CURRENT_TIME", "CURRENT_TIMESTAMP", "DENSE_RANK", "ELEMENT", "EXP", "FIRST_VALUE", "FUSION", "GROUPING", "HOUR", "LAG", "LEAD", "LEFT", "LAST_VALUE", "LN", "LOCALTIME", "LOCALTIMESTAMP", "LOWER", "MAX", "MIN", "MINUTE", "MOD", "MONTH", "NTH_VALUE", "NTILE", "NULLIF", "OCTET_LENGTH", "PERCENT_RANK", "POWER", "RANK", "REGR_COUNT", "REGR_SXX", "REGR_SYY", "RIGHT", "ROW_NUMBER", "SECOND", "SQRT", "STDDEV_POP", "STDDEV_SAMP", "SUM", "UPPER", "TRUNCATE", "USER", "VAR_POP", "VAR_SAMP", "YEAR", "CURRENT_CATALOG", "CURRENT_DEFAULT_TRANSFORM_GROUP", "CURRENT_PATH", "CURRENT_ROLE", "CURRENT_SCHEMA", "CURRENT_USER", "SESSION_USER", "SYSTEM_USER", "NEW", "CASE", "CURRENT", "CURSOR", "ROW", "(", "SELECT", "VALUES", "TABLE", "DESCRIBE", "DELETE", "UPDATE", "MERGE", "CALL"])
```

**To Reproduce**
Execute the following recipe against a Druid v27.0.0 broker:
```yaml
source:
  type: druid
  config:
    # Coordinates
    host_port: "localhost:8082"
    profiling:
      enabled: True
      include_field_null_count: true
      include_field_min_value: true
      include_field_max_value: true
      include_field_mean_value: true
      include_field_median_value: true
      include_field_stddev_value: true
      include_field_distinct_value_frequencies: true
      limit: 10000
    
sink:
  type: "datahub-kafka"
  config:
    connection:
      bootstrap: "localhost:9094"
      schema_registry_url: "http://localhost:8080/schema-registry/api/"
```

**Expected behavior**
To get profiling data into DataHub for a Druid table instead of getting an error like:
```
[2023-11-16 14:31:23,136] ERROR    {datahub.ingestion.source.ge_data_profiler:1094} - Encountered exception while profiling <table>
```

**Desktop:**
 - OS: [macOS Ventura]
