### ISSUE TITLE
acryl-datahub[mongodb] > field schemaSamplingSize does not work as expected

### ISSUE THREAD

**Issue by diegoreico** [datahub-project/datahub#9287]
Field schemaSamplingSize inside the [Datahub mongodb connector documentation](https://datahubproject.io/docs/generated/ingestion/sources/mongodb) says the following:

```
Number of documents to use when inferring schema size. If set to 0, all documents will be scanned.
Default: 1000
```
I was performing a proof of concept over a small mongodb database in which I wanted to scan all documents, and I have the following error

```
....
datahub.ingestion.run.pipeline.PipelineInitError: Failed to configure the source (mongodb): 1 validation error for MongoDBConfig
schemaSamplingSize
  ensure this value is greater than 0 (type=value_error.number.not_gt; limit_value=0)
Failed to configure the source (mongodb): 1 validation error for MongoDBConfig
```
And this is the connecor config i was using:

```
source:
    type: mongodb
    config:
        connect_uri: 'mongodb://xx.xx.xx.xx:27017'
        username: xxxxx
        password: xxxxx
        enableSchemaInference: true
        useRandomSampling: true
        maxSchemaSize: 300
        database_pattern:
            allow:
                - xxxxx
        schemaSamplingSize: 0

```

Taking a peak into the connector, the code expects the `schemaSamplingSize` to be null instead of 0
https://github.com/datahub-project/datahub/blob/15e68bb77199ba54b77df8ffa0df13b7c1fe16ad/metadata-ingestion/src/datahub/ingestion/source/mongodb.py#L186 

But providing a ` schemaSamplingSize: null` or  `schemaSamplingSize: None` also causes an error:
```
pymongo.errors.OperationFailure: size argument to $sample must be a number, full error: {'ok': 0.0, 'errmsg': 'size argument to $sample must be a number', 'code': 28746, 'codeName': 'Location28746'}
```

Internal code documentation also reflects this beheaviour:
https://github.com/datahub-project/datahub/blob/15e68bb77199ba54b77df8ffa0df13b7c1fe16ad/metadata-ingestion/src/datahub/ingestion/source/mongodb.py#L253

As far as I have reached, i think that it's imposible to force a full mongodb collection scan, because the yaml parser + validator forces to provide a value greater than 0, but internal code checks for null

**Expected behavior**
Providing a 0 value for schemaSamplingSize should scan a full mongodb collection without errors and web page documentation should also reflect that.
