### ISSUE TITLE
Tableau ingestion error: Cannot return null for non-nullable type: \'TableauUser\' within parent 

### ISSUE THREAD

**Issue by YuriyGavrilov** [datahub-project/datahub#9398]
**Describe the bug**

Just receiving this bug when try to upload all tableau server more than 100 projects and 5 level subprojects. 

```
packages/datahub/ingestion/source/tableau.py", line 733, in '
           'get_connection_object_page\n'
           '    raise RuntimeError(f"Query {connection_type} error: {errors}")\n'
           'RuntimeError: Query workbooksConnection error: [{\'message\': "Cannot return null for non-nullable type: \'TableauUser\' within parent '
           '\'Workbook\' (/workbooksConnection/nodes[0]/owner)", \'path\': [\'workbooksConnection\', \'nodes\', 0, \'owner\'], \'locations\': None, '
           "'errorType': 'DataFetchingException', 'extensions': None}]\n"
           '[2023-12-06 12:37:01,305] INFO     {datahub.ingestion.reporting.file_reporter:52} - Wrote CANCELLED report successfully to '
           "<_io.TextIOWrapper name='/tmp/datahub/ingest/65528fe7-3e80-430c-b7c5-d40e09a69dab/ingestion_report.json' mode='w' encoding='UTF-8'>\n"
           '[2023-12-06 12:37:01,306] INFO     {datahub.cli.ingest_cli:134} - Source (tableau) report:\n'
```

**To Reproduce**
1. Go to 'ingestion'
2. Click on 'add'
3. Set up 'Tableau'
4. Run
5. See errors 

**Expected behavior**
Successful upload without error / half-result could be just miss workbooks or other tableau entities with errors and continue work not just cancelation ingestion job for all tableau. Better to see count with errors and without. 

**Screenshots**
![image](https://github.com/datahub-project/datahub/assets/44679014/49a6ee53-19d4-46cb-a29d-8496169e9f2d)

**Desktop (please complete the following information):**

**Additional context**
full log here: 
[exec-urn_li_dataHubExecutionRequest_65528fe7-3e80-430c-b7c5-d40e09a69dab.log](https://github.com/datahub-project/datahub/files/13587499/exec-urn_li_dataHubExecutionRequest_65528fe7-3e80-430c-b7c5-d40e09a69dab.log)

Ingestion recipe: 

```
transformers:
    -
        type: simple_add_dataset_tags
        config:
            tag_urns:
                - 'urn:li:tag:product.BI'
sink:
    type: datahub-rest
    config:
        server: 'http://datahub-gms-datahub-gms:8080'
        token: '${ingestions_by_yua}'
        max_threads: 1
source:
    type: tableau
    config:
        ingest_owner: true
        platform_instance: TABLEAUDEV
        connect_uri: 'https://XXXXXXX'
        ingest_tables_external: true
        ingest_tags: false
        page_size: 5
        stateful_ingestion:
            enabled: true
            remove_stale_metadata: true
        token_name: datahub_tableau_dev
        token_value: '${Tableau_dev_token}'
pipeline_name: my_tableau_pipeline_1
datahub_api:
    server: 'http://datahub-gms-datahub-gms:8080'

```
