### ISSUE TITLE
[Kafka emitter][browsePathsV2 aspect duplicates the platform instance]

### ISSUE THREAD

**Issue by jGuzmanSan** [datahub-project/datahub#9448]
**Describe the bug**
Having multiple kafka broker (MSK, one per region) and setting the [Platform Instance](https://datahubproject.io/docs/platform-instances) in the https://datahubproject.io/docs/generated/ingestion/sources/kafka/ , the navigation tree is duplicating the platform instance all the times.

**To Reproduce**

1.- Configure the kafka emitter for ingesting all topics from different kafka brokers, i.e. using `"eu-central-1"` as `platform instance`
2.- Once the topics are sent, the browsepathv2 aspect for each topic is created like:
```
# urn	aspect	version	metadata	systemmetadata	createdon	createdby	createdfor
urn:li:dataset:(urn:li:dataPlatform:kafka,eu-central-1.DataHubUsageEvent_v1,DEV)	browsePathsV2	0	{"path":[{"urn":"urn:li:dataPlatformInstance:(urn:li:dataPlatform:kafka,eu-central-1)","id":"urn:li:dataPlatformInstance:(urn:li:dataPlatform:kafka,eu-central-1)"},{"id":"eu-central-1"}]}	{"lastRunId":"kafka-2023_12_12-17_07_36","lastObserved":1702397259840,"runId":"kafka-2023_12_12-14_19_30"}	2023-12-12 13:19:34.856000	urn:li:corpuser:__datahub_system	

```
3.- In the ui, search all the datasets of the Kafka platform and expand the folders created in the navigation-menu, the platform instance is displayed twice.

**Expected behavior**
The platform instance is displayed just once. 

**Screenshots**

<img width="349" alt="image" src="https://github.com/datahub-project/datahub/assets/61798774/80fc01b5-b4b4-4ff6-9bc3-1eb3de1f71d9">

**Desktop (please complete the following information):**
 ```Cli report:
{'cli_version': '0.12.1.0',
 'cli_entry_location': '/.pyenv/versions/3.10.10/lib/python3.10/site-packages/datahub/__init__.py',
 'py_version': '3.10.10 (main, Apr 14 2023, 09:07:53) [Clang 14.0.3 (clang-1403.0.22.14.1)]',
 'py_exec_path': '.pyenv/versions/3.10.10/bin/python3',
 'os_details': 'macOS-14.1.2-arm64-arm-64bit',
 'peak_memory_usage': '128.39 MB',
 'mem_info': '128.39 MB',
 'peak_disk_usage': '214.87 GB',
 'disk_info': {'total': '494.38 GB', 'used': '214.87 GB', 'free': '279.52 GB'}}
Source (kafka) report:... 
```

**Additional context**
The setup used for emitting kafka metadata is: 

```
pipeline_name: "kafka-emitter-schemas-ec1"
datahub_api:
    server: "http://localhost:8080"
source:
    type: kafka
    config:
        connection:
            consumer_config:
                security.protocol: PLAINTEXT
                sasl.mechanism: PLAIN
            bootstrap: localhost:9092
            schema_registry_url: http://localhost:8081
        env: "DEV"
        platform_instance: "eu-central-1"
sink:
  type: "datahub-kafka"
  config:
    connection:
      bootstrap: localhost:9092
      schema_registry_url: http://localhost:8081
```
