### ISSUE TITLE
Teradata Ingestion:  Profiling fails with invalid argument

### ISSUE THREAD

**Issue by Pibbers** [datahub-project/datahub#9509]
I keep getting an error when I try to profile data on Teradata.  This is the error which is reported in the logs:

`TypeError: Invalid argument(s) 'max_overflow' sent to create_engine(), using configuration TeradataDialect/SingletonThreadPool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.`

This is the recipe I am using:

```
pipeline_name: my-teradata-ingestion-pipeline
source:
    type: teradata
    config:
        host_port: 'clearscape.teradata.com:1025'
        username: datahub
        password: XXXXXXX
        include_table_lineage: true
        include_usage_statistics: true
        stateful_ingestion:
            enabled: true
        database_pattern:
            allow:
                - jaffle_shop
        profiling:
            enabled: true
```
I have attached a log run in debug mode.  I believe this error maybe down to the Teradata SQLAlchemy driver not supporting all connection parameters.  These are the only supported ones according to the documentation ( https://pypi.org/project/teradatasqlalchemy/#ConnectionParameters )

Using UI with CLI v0.12.1
Teradata Vantage  RDBMS v17.20
Teradata SQLAlchemy 17.20

[exec-urn_li_dataHubExecutionRequest_f0aa1b0e-b274-48b1-b03d-d881bf52650a.log](https://github.com/datahub-project/datahub/files/13751411/exec-urn_li_dataHubExecutionRequest_f0aa1b0e-b274-48b1-b03d-d881bf52650a.log)
