### ISSUE TITLE
Could not use specified custom data roles inside transformer

### ISSUE THREAD

**Issue by YuriyGavrilov** [datahub-project/datahub#9839]
**Describe the bug**

We create few type or roles like 

![image](https://github.com/datahub-project/datahub/assets/44679014/4a69707b-da3f-46e7-b55d-eaa5473ac45b)

so we can't use it inside transformer like:

```
transformers:
  - type: "pattern_add_dataset_ownership"
    config:
      owner_pattern:
        rules:
          ".*example1.*": ["urn:li:corpuser:username1"]
          ".*example2.*": ["urn:li:corpuser:username2"]
      ownership_type: "Space_Admin"
```

**To Reproduce**
1. Go to 'admin'
2. Click on 'create custom role'
3. Create transformer with this new role 
4. See error:
```          '  File "/tmp/datahub/ingest/venv-trino-v0.12.0/lib/python3.10/site-packages/datahub/emitter/mce_builder.py", line 364, in '
           'validate_ownership_type\n'
           '    raise ValueError(f"Unexpected ownership type: {ownership_type}")\n'
           'ValueError: Unexpected ownership type: Space_Admin\n'
           '\n'
           'The above exception was the direct cause of the following exception:\n'
           '\n' "
```

**Expected behavior**

Simply add any custom roles

**Screenshots**
![image](https://github.com/datahub-project/datahub/assets/44679014/87e29d5d-04ba-4354-b936-2483f1944deb)

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Browser [e.g. chrome]
 - Version [e.g. 0.12]

**Additional context**
There no info how to create new role and use it in transformer
