### ISSUE TITLE
Wrong database name after Oracle ingestion

### ISSUE THREAD

**Issue by haeniya** [datahub-project/datahub#9931]
**Describe the bug**
When ingesting Oracle datasets with a service name specified in the ingestion recipe, we experience the following issue:
![image](https://github.com/datahub-project/datahub/assets/12571550/b5096c13-c1fb-4c8a-aa39-d43f745e0ba8)

The database name displayed in the UI is a random container URN. There was already another issue that seems related: https://github.com/datahub-project/datahub/issues/8148.
And there's also a discussion in Slack with no recent activity though: https://datahubspace.slack.com/archives/CUMUWQU66/p1652894449976439 

Our recipe looks something like this:
```
source:
  type: oracle
  config:
    host_port: 'example-host.com:1521'
    service_name: example.prod.dbs
    username: '${ORACLE_USER}'
    password: '${ORACLE_PASSWORD}'
    platform_instance: example
    view_pattern:
      allow:
        - '.*EXAMPLE_VIEW.*'
      deny: []
      ignoreCase: true
    schema_pattern:
      allow:
        - 'EXAMPLE_SCHEMA.*'
      deny: []
      ignoreCase: true
    include_tables: false
    env: PROD
sink:
  type: datahub-rest
  config:
    server: '${DATAHUB_GMS_URL}'
    token: '${DATAHUB_GMS_TOKEN}'
```

**To Reproduce**
1. Ingest Oracle datasets with a recipe like the one above and a service name specified.

**Expected behavior**
Correct service name displayed in the UI.

**Additional context**
We use Datahub version 0.12.0 and the Oracle ingestion CLI in version 0.12.1.0.
